### ISSUE TITLE
KeyError: 'content'

### ISSUE THREAD

**Issue by shaiss** [TransformerOptimus/SuperAGI#100]
Getting a KeyError: 'content'.  I'm trying to debug this and couldn't find a similar issue. I'm on windows with python 3.10.11

```
Enter your Goals seperated by ',':
make a simple hello world webpage

____________________Iteration : 1________________________


I am Super AGI. My role is To solve any complex problems for you


Goals:
1. make a simple hello world webpage


Tools:
1. Google Search
2. write_file

| Thinking...Exception: The model: `gpt-4` does not exist


Traceback (most recent call last):
  File "C:\Users\Shai\Documents\SuperAGI\test.py", line 42, in <module>
    superagi.execute(user_goal)
  File "C:\Users\Shai\Documents\SuperAGI\superagi\agent\super_agi.py", line 123, in execute
    if response['content'] is None:
KeyError: 'content'
(venv) PS C:\Users\Shai\Documents\SuperAGI>
```

**Comment by link82** [comment]
Same problem here.
I've also tried to change model I'm using to `gpt-3.5-turbo-0301` or `gpt-3.5-turbo` with no luck.

Actually I have an active premium subscription with chatGPT service and I subscribed to the free tier of Pinecone.

It seems that client is not receiving any answer from the API but I'm sure the API key I provided is working: I've just tested it with my ruby client.

**Comment by Fluder-Paradyne** [comment]
| Thinking...Exception: The model: `gpt-4` does not exist

occurs when you don't have access gpt-4 api access

@link82 chatGPT premium does not give gpt-4 api access

we are working on make it work with gpt-3.5-turbo

**Comment by Autocop-Agent** [comment]
We have added the GPT 3.5 capability. You can try it out

**Comment by neelayan7** [comment]
Closing this as fixed.
