### ISSUE TITLE
problem creating knowledge

### ISSUE THREAD

**Issue by ivan-vilches** [TransformerOptimus/SuperAGI#1016]
i added 
#####################------------------SYSTEM KEYS-------------------------########################
PINECONE_API_KEY: myapi
PINECONE_ENVIRONMENT: environment

after that i run superagi onl ocalhost:3000

on settings i connect a database from pinecone and ask me again for the api i pull the data and connect with success , 
but when i create an agent it ask me for create or choose an index but i cant choose it, i have the option to create a new knowledge but still not work, not sure if are a tutorial or is a bug.
thanks you.

**Comment by eqxwow** [comment]
Hey @ivan-vilches You are following the right steps. I think it could be an issue with index dimensions, the dimensions should be 1536. Please check this once. If you are still facing the error, join our Discord community https://discord.gg/AWMkBxfJ and ping me. Will help troubleshoot this.

**Comment by coder5492** [comment]
We've marked this GitHub issue as resolved for the time being. If it's not resolved to your satisfaction, please feel free to reopen it. Your involvement in our community means a lot to us! 😊
