### ISSUE TITLE
No Model Options Listed under "Model" During Create Agent

### ISSUE THREAD

**Issue by securityvoid** [TransformerOptimus/SuperAGI#1052]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

After doing the following on a fresh git pull from the SuperAGI Repo:
docker-compose up --build

The following are the only warnings I see in the log:
```
superagi-backend-1          | Installing collected packages: typing_extensions, pytest, superagi-tools
superagi-backend-1          |   Attempting uninstall: typing_extensions
superagi-backend-1          |     Found existing installation: typing_extensions 4.5.0
superagi-backend-1          |     Uninstalling typing_extensions-4.5.0:
superagi-celery-1           |       Successfully uninstalled pytest-7.3.2
superagi-backend-1          |       Successfully uninstalled typing_extensions-4.5.0
superagi-backend-1          |   Attempting uninstall: pytest
superagi-backend-1          |     Found existing installation: pytest 7.3.2
superagi-backend-1          |     Uninstalling pytest-7.3.2:
superagi-celery-1           | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
superagi-celery-1           | llama-index 0.6.35 requires typing-extensions==4.5.0, but you have typing-extensions 4.7.1 which is incompatible.
superagi-celery-1           | qdrant-client 1.3.1 requires typing-extensions<4.6.0,>=4.0.0, but you have typing-extensions 4.7.1 which is incompatible.
superagi-celery-1           | Successfully installed pytest-7.4.0 superagi-tools-1.0.6 typing_extensions-4.7.1
superagi-backend-1          | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
superagi-backend-1          | llama-index 0.6.35 requires typing-extensions==4.5.0, but you have typing-extensions 4.7.1 which is incompatible.
superagi-backend-1          | qdrant-client 1.3.1 requires typing-extensions<4.6.0,>=4.0.0, but you have typing-extensions 4.7.1 which is incompatible.
superagi-backend-1          | Successfully installed pytest-7.4.0 superagi-tools-1.0.6 typing_extensions-4.7.1
```

```
superagi-backend-1          | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
superagi-backend-1          | llama-index 0.6.35 requires typing-extensions==4.5.0, but you have typing-extensions 4.7.1 which is incompatible.
superagi-backend-1          | qdrant-client 1.3.1 requires typing-extensions<4.6.0,>=4.0.0, but you have typing-extensions 4.7.1 which is incompatible.
superagi-backend-1          | Successfully installed pytest-7.4.0 superagi-tools-1.0.6 typing_extensions-4.7.1
```

It does eventually get to:
```
superagi-backend-1          | 2023-08-13 18:44:53 UTC - Super AGI - INFO - [/app/superagi/models/db.py:43] - Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-backend-1          | INFO:     Started server process [42]
superagi-backend-1          | INFO:     Waiting for application startup.
superagi-backend-1          | 2023-08-13 18:44:56 UTC - Super AGI - INFO - [/app/main.py:176] - Running Startup tasks
superagi-backend-1          | 2023-08-13 18:44:56 UTC - Super AGI - INFO - [/app/main.py:180] - User(id=1, name='SuperAGI User', email='super6@agi.com', password='pass@123',organisation_id=1)
superagi-backend-1          | 2023-08-13 18:44:56 UTC - Super AGI - INFO - [/app/main.py:183] - Organisation(id=1, name='Default Organization - 1')
superagi-backend-1          | 2023-08-13 18:45:02 UTC - Super AGI - INFO - [/app/superagi/helper/tool_helper.py:265] - Toolkits Registered Successfully for Organisation ID : 1!
superagi-backend-1          | 2023-08-13 18:45:07 UTC - Super AGI - INFO - [/app/superagi/helper/tool_helper.py:265] - Toolkits Registered Successfully for Organisation ID : 1!
superagi-backend-1          | 2023-08-13 18:45:07 UTC - Super AGI - INFO - [/app/main.py:190] - Successfully registered local toolkits for all Organisations!
superagi-backend-1          | INFO:     Application startup complete.
```

Once it fully loads up I can navigate to:
https://localhost:3000

If I then go to:
`Agents -> Create Agent -> Build From Scratch`

There are no options listed under model, just an arrow that won't reveal anything.

If I fill out the rest of the fields and click, "Create and Run". I receive the error:
"Your key does not have access to the selected model"

This makes sense because a model wasn't chosen because none are listed.

Within the config.yaml file I have the fields filled out for:
OPENAI_API_KEY
GOOGLE_API_KEY
SEARCH_ENGINE_ID

Per the instructions from:
https://www.youtube.com/watch?v=Unj5NLNTkLY

Its worth noting that I signed up for a trial under OpenAPI awhile back and it expired. I have since setup my credit card number so it should be setup to still work. I have not tested this independently, but as I'm typing this I'll definitely put that on the list of things to do.

I have tried the configuration setting:
MODEL_NAME

As the default "gpt-3.5-turbo-0301" and the value "gpt-3.5-turbo"

I'm hoping someone can recognize what the issue is.

### How to replicate your Issue?

`Agents -> Create Agent -> Build From Scratch`

There are no options listed under model, just an arrow that won't reveal anything.

If I fill out the rest of the fields and click, "Create and Run". I receive the error:
"Your key does not have access to the selected model"

This makes sense because a model wasn't chosen because none are listed.

### Upload Error Log Content

Relevant Log content is in initial discussion.

**Comment by securityvoid** [comment]
I independently validated my OpenAPI key doing some langchain calls and confirmed its working properly. Not sure why SuperAGI won't work. Hopefully someone has some ideas, or at least where to look for more useful errors :-).

**Comment by securityvoid** [comment]
I worked around the issue by inserting a line after line 166 in "controllers/organisation.py" to hard-code things to OpenAI:
`    model_source = Configuration(id=1, organisation_id=1, key="model_source", value="OpenAi")`

How is this value supposed to be initially set in the database so it doesn't have to be hard-coded? Didn't see anything in config.py that seemed to match the name, and in 30 minutes of poking around I could not figure out how its supposed to be set initially.

**Comment by securityvoid** [comment]
BTW, I figured this out because the following URL was returning an HTTP 400 on load of the agent page where the models should display:
http://localhost:3000/api/organisations/llm_models

**Comment by digetier** [comment]
@securityvoid thanks for raising the issue. I encounter the same problem and would love to get some feedback on how to solve it!

**Comment by lunarthegrey** [comment]
Same exact problem here. Was going to try out SuperAGI for the first time and I have encountered this bug.

I see nonstop websocket connections, unsure if that's related:

<img width="1466" alt="Screenshot 2023-08-17 at 3 00 42 PM" src="https://github.com/TransformerOptimus/SuperAGI/assets/8747426/730cf4ca-ae64-4e3b-b04e-ef828563063e">

```
superagi-proxy-1            | 2023/08/17 19:57:21 [error] 31#31: *176 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.19.0.1, server: , request: "GET /_next/webpack-hmr HTTP/1.1", upstream: "http://172.19.0.2:3000/_next/webpack-hmr", host: "localhost:3000"
```

At the moment this makes SuperAGI unusable :(

**Comment by securityvoid** [comment]
Okay, had a few minutes to isolate this a bit further.

If in docker you blow away all your containers, images, and volumes and you do a:
`git checkout 84b593ce170ee22725cbf1589818f8b336eba30d`

Before your:
`docker-compose up --build`

It seems to run properly. 

If you do the same thing again, but this time doing:
`git checkout 4b202babf8db14600ed39742518a7f290fad0610`

It fails and doesn't load the models. That commit is the next commit. As a result, something in 4b202babf8db14600ed39742518a7f290fad0610 broke the loading of models.

**Comment by securityvoid** [comment]
Okay, this is a simple issue.

The documentation has not been updated, but you should not be entering the OpenAI key into the config.yaml file like the instructions state. Instead you should be navigating to the web-app, choosing "Settings" and entering the details there.

If you do that, everything works and is happy. This is just an indication that the doc needs to be update.

**Comment by chris-aeviator** [comment]
@securityvoid it woul be very helpful if the main entrypoint (Readme) could be cleaned of irrelevant info and relevant issue comments like yours linked. It saves folks hours of frustration. Unfortunately your issue template does not allow for this kind of issue being filed.
