### ISSUE TITLE
No module named 'superagi.tools....'

### ISSUE THREAD

**Issue by IANTHEREAL** [TransformerOptimus/SuperAGI#1053]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

MacOS

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Tools

### Describe your issue.

When using the latest release, I can't adding external tool.

I would like to know Is there a problem with the code refactoring of the "tool builder" module, and how to fix it now?

### How to replicate your Issue?

Just follow add customing tool instruction

### Upload Error Log Content
```
superagi-celery-1           | 2023-08-14 02:44:18 UTC - Super AGI - INFO - [/app/superagi/agent/tool_builder.py:67] - Loading module superagi.tools.GreetingTool.greetings_toolkit from tool Greetings Tool 
superagi-celery-1           | [2023-08-14 02:44:18,663: INFO/ForkPoolWorker-8] Loading module superagi.tools.GreetingTool.greetings_toolkit from tool Greetings Tool 
superagi-celery-1           | 2023-08-14 02:44:18 UTC - Super AGI - INFO - [/app/superagi/jobs/agent_executor.py:81] - Exception in executing the step: No module named 'superagi.tools.GreetingTool' 
superagi-celery-1           | [2023-08-14 02:44:18,663: INFO/ForkPoolWorker-8] Exception in executing the step: No module named 'superagi.tools.GreetingTool' 
```

**Comment by luciferlinx101** [comment]
@IANTHEREAL Can you try it again and check if the issue persists or resolved?

**Comment by IANTHEREAL** [comment]
@luciferlinx101 Yes, it fixed. Thanks
