### ISSUE TITLE
Constraints incorrectly populated

### ISSUE THREAD

**Issue by JamesHutchison** [TransformerOptimus/SuperAGI#1090]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Codespaces

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

Sorry, in the middle of the hackathon so I can't really investigate, but noticed this on a rerun.
![mutated-constraints-rerun](https://github.com/TransformerOptimus/SuperAGI/assets/122519877/721f1c2f-2751-45db-87a9-038709d6fb4b)

### How to replicate your Issue?

Not sure. I'm running in codespaces so totally possible I somehow did this although I'm not sure how as I'm only working on a toolkit and not modifying the SuperAGI code

### Upload Error Log Content

...

**Comment by JamesHutchison** [comment]
When I get a chance I'll see if I can repro

**Comment by coder5492** [comment]
@JamesHutchison Could you please describe on how the constraints are incorrectly populated?

**Comment by JamesHutchison** [comment]
Oh I forgot about it this. I think when I used it recently on a newer version I no longer was seeing the issue. 

This appeared to be incorrectly copying the constraints and was adding brackets and quotes.

I'll confirm and close if that's the case

**Comment by JamesHutchison** [comment]
Seems fixed. This is from a rerun. Closing
![constraints](https://github.com/TransformerOptimus/SuperAGI/assets/122519877/8539bc3a-f0c6-4322-866d-fa01ca09b026)
