### ISSUE TITLE
Hardcoded Credentials in Docker Image superagidev/superagi:main

### ISSUE THREAD

**Issue by dotnetautor** [TransformerOptimus/SuperAGI#1096]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Linux

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

The Docker image superagidev/superagi:main contains hardcoded credentials and host name. Particularly concerning is the database password which is set as "password". This design restricts users from setting their own security credentials.

Expected Behavior:
The Docker image should not contain any hardcoded credentials, allowing users to specify their own, especially for security-sensitive components like database passwords.

Workaround:
For now, users can create a copy of the affected configuration file and bind it as a volume in the Docker Compose setup.
```yaml
volumes:
      - "./alembic.ini:/app/alembic.ini"  
```

See error log:
```
psycopg2.OperationalError: could not translate host name "super__postgres" to address: Temporary failure in name resolution
``` 

### How to replicate your Issue?

To reproduce the issue, follow the steps in the instructions at: https://hub.docker.com/r/superagidev/superagi.
Before starting, replace the database connection credentials with your own in  `docker-compose.yaml` and `config.yaml`.

### Upload Error Log Content

psycopg2.OperationalError: could not translate host name "super__postgres" to address: Temporary failure in name resolution

**Comment by Fluder-Paradyne** [comment]
Hi @dotnetautor 
thanks for reporting this.

I'll fix this asap
