### ISSUE TITLE
Duckduck go integration

### ISSUE THREAD

**Issue by mayuroks** [TransformerOptimus/SuperAGI#118]
Is there are support for agent to use Duckduck go ?

**Comment by nmcbride** [comment]
DuckDuckGo would be good, SearXNG would be better.

**Comment by vaibhavnayel** [comment]
@TransformerOptimus  I'd like to take this up as a first issue.

**Comment by MaHDiaLaGaB** [comment]
@TransformerOptimus is this ticket still open? or under development?
