### ISSUE TITLE
ERROR: config.yaml file not found. Please create the config.yaml file.

### ISSUE THREAD

**Issue by AlphaAmirzh** [TransformerOptimus/SuperAGI#120]
Hi

I did everything exactly how it was described in the description, but I keep getting the following error:
ERROR: config.yaml file not found. Please create the config.yaml file.

I have tried several fixes, but nothing seems to work. What could be the reason?

Thank you.

**Comment by Fluder-Paradyne** [comment]
did you create the config.yaml file based on config_template.yaml

**Comment by TransformerOptimus** [comment]
@AlphaAmirzh  To create the config do this,
`cp config_template.yaml config.yml`

Then open the `config.yaml` and add necessary keys.

And finally run, `./run.sh` to run the agent

**Comment by AlphaAmirzh** [comment]
Hi, thank you for your responses, yes I created the config.yaml file based on config_template.yaml and now I also tried TransformerOptimus solution, but I still get the same error:

ERROR: config.yaml file not found. Please create the config.yaml file.


I am attaching a screenshot, maybe that could help:

![Screenshot 2023-05-27 171155](https://github.com/TransformerOptimus/SuperAGI/assets/126407836/0f06f9aa-7308-4c19-8493-8e0a9e54acdf)

**Comment by Fluder-Paradyne** [comment]
try `.\run.bat` instead of `run.sh`

**Comment by AlphaAmirzh** [comment]
I have been using .\run.bat thats when the error message appears.

**Comment by neelayan7** [comment]
Closing this as this is solved in the newer version updates
