### ISSUE TITLE
Slack tool

### ISSUE THREAD

**Issue by mayuroks** [TransformerOptimus/SuperAGI#125]
I would like agent to read all unread messages and summarize them for me and tell if there some important action item I need to work on. Also any research I do share what with me or in a slack channel.

**Comment by Autocop-Agent** [comment]
Working on it

**Comment by Arkajit-Datta** [comment]
Hey, I have raised PR #135. This currently can read unread messages and formats them in a dictionary for further summarization. Also can send Slack messages both individually and in channels. The Summarization and notifying part can be taken up further. 

@Autocop-Agent if you haven't made a huge progress on the feature, would you mind if I can proceed on the same? 

Thanks!

**Comment by Arkajit-Datta** [comment]
Hey @mayuroks the PR #135 got merged. what are the next steps in the Slack Tool? or is there anything else you'll want me to take up?

**Comment by neelayan7** [comment]
We have added Slack Tool. Currently it has functionality to write messages only. @Arkajit-Datta you can pick up the next steps where we want to read messages as well.

**Comment by Arkajit-Datta** [comment]
sure @neelayan7 lets prolly discuss what all functionalities are required. That will help us to structure the tool well.

**Comment by neelayan7** [comment]
We can start with the Read Messages and defining the scopes required for it. We can connect offline for this as well. Ping me, it's @rick_7 on discord.

**Comment by Arkajit-Datta** [comment]
hey sure neelayan!
