### ISSUE TITLE
Deployment Getting Failed

### ISSUE THREAD

**Issue by ganeshbehera** [TransformerOptimus/SuperAGI#1352]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Linux

### Which branch of SuperAGI are you using?

Dev (branch)

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Deployment Getting failed, Please fix it 

### Upload Error Log Content

[2023-10-25 09:15:51] ERROR:    Traceback (most recent call last): [2023-10-25 09:15:51]   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan [2023-10-25 09:15:51]     async with self.lifespan_context(app) as maybe_state: [2023-10-25 09:15:51]   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__ [2023-10-25 09:15:51]     await self._router.startup() [2023-10-25 09:15:51]   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup [2023-10-25 09:15:51]     await handler() [2023-10-25 09:15:51]   File "/app/main.py", line 249, in startup_event [2023-10-25 09:15:51]     local_llm_model_config() [2023-10-25 09:15:51]   File "/app/main.py", line 221, in local_llm_model_config [2023-10-25 09:15:51]     existing_models_config = session.query(ModelsConfig).filter(ModelsConfig.org_id == default_user.organisation_id, ModelsConfig.provider == 'Local LLM').first() [2023-10-25 09:15:51] AttributeError: 'NoneType' object has no attribute 'organisation_id' [2023-10-25 09:15:51]  [2023-10-25 09:15:51] ERROR:    Application startup failed. Exiting.

**Comment by Threchette** [comment]
same here

**Comment by Michspirit99** [comment]
I am also getting this as well. I've redownloaded the application and i still get this error.

**Comment by Jldouglas84** [comment]
I also get this error.

When I try to load localhost:3000 I see the SuperAGI logo in the top left and Ïnitailizing SuperAGI... loading and get no further

This is happening in the superagi-backend-1 container in docker using superagi-backend

**Comment by c0d3x** [comment]
Same issue on Mac OS 14

**Comment by ryan-james-smith** [comment]
same error here, if I take the log back a couple of extra lines i have:
`superagi-backend-1          | 2023-10-27 19:42:38 UTC - Super AGI - INFO - [/app/main.py:197] - Running Startup tasks
superagi-backend-1          | 2023-10-27 19:42:38 UTC - Super AGI - INFO - [/app/main.py:201] - None
superagi-backend-1          | 2023-10-27 19:42:39 UTC - Super AGI - INFO - [/app/superagi/models/workflows/agent_workflow_step.py:157] - Finding or creating wait step
superagi-backend-1          | ERROR:    Traceback (most recent call last):
superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
superagi-backend-1          |     async with self.lifespan_context(app) as maybe_state:
superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
superagi-backend-1          |     await self._router.startup()
superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
superagi-backend-1          |     await handler()
superagi-backend-1          |   File "/app/main.py", line 249, in startup_event
superagi-backend-1          |     local_llm_model_config()
superagi-backend-1          |   File "/app/main.py", line 221, in local_llm_model_config
superagi-backend-1          |     existing_models_config = session.query(ModelsConfig).filter(ModelsConfig.org_id == default_user.organisation_id, ModelsConfig.provider == 'Local LLM').first()
superagi-backend-1          | AttributeError: 'NoneType' object has no attribute 'organisation_id'
superagi-backend-1          | 
superagi-backend-1          | ERROR:    Application startup failed. Exiting.`

Where the second line says None this is a log of default_user.
The Errr on line 221 is trying to use default_user.organisation_id however as per the previous log our default_user is None so it does not contain an organisation_id.

Unfortunately I can understand why I see the error, but I have not the skill (yet) to go about finding a solution.

**Comment by gwickman** [comment]
I'm getting the same issue on Windows 11 using the docker install. It seems like the default_user for the postgress database "super6@agi.com" should exist but doesn't?

**Comment by izevar** [comment]
Same issue on Mac M2

**Comment by izevar** [comment]
I found a workaround
After the --build command the DB do not have any default user or organization created.
So if you modify the docker-compose file to allow to expose the Postgres ports you can manually create an user and an organization after that do restart the containers and should work.

it's a workaround not a fix.

**Comment by alangunning** [comment]
Getting the same error. It appears to have been introduced by PR: https://github.com/TransformerOptimus/SuperAGI/pull/1351


For anyone blocked while awaiting a fix, I was able to succesfully startup by commenting out this line.
https://github.com/TransformerOptimus/SuperAGI/blob/b96fdabcf6a20d4309bfb5ff99a144d59cd74dd0/main.py#L249C18-L249C18

**Comment by Michspirit99** [comment]
> Getting the same error. It appears to have been introduced by PR: #1351
> 
> For anyone blocked while awaiting a fix, I was able to succesfully startup by commenting out this line. https://github.com/TransformerOptimus/SuperAGI/blob/b96fdabcf6a20d4309bfb5ff99a144d59cd74dd0/main.py#L249C18-L249C18

This is a very good work around.

Specifically this line

![image](https://github.com/TransformerOptimus/SuperAGI/assets/11279621/3f15a266-d937-4500-80c1-01ba540180a3)

**Comment by rounak610** [comment]
We have fixed this issue in #1353 (fixes for the main branch) and #1354 (fixes for the dev branch).
