### ISSUE TITLE
Ollama support?

### ISSUE THREAD

**Issue by BluePhi09** [TransformerOptimus/SuperAGI#1365]
Is there any way to use Ollama to host the llm models?

**Comment by MikeyBeez** [comment]
This should be easy:  
from langchain.llms import Ollama
ollama = Ollama(base_url='http://localhost:11434', model="llama2")
response = ollama(prompt)

Cheers!

**Comment by shaileshjswl** [comment]
# Import the Ollama class from langchain.llms
from langchain.llms import Ollama

# Create an instance of the Ollama class with specified parameters
ollama = Ollama(base_url='http://localhost:11434', model="llama2")

# Define the prompt you want to send to the Ollama model
prompt = "Your prompt goes here"

# Make a request to the Ollama model with the provided prompt
response = ollama(prompt)

# Print the response from the Ollama model
print(response)

**Comment by motoxxx138** [comment]
Same question; how do we utilize this to use ollama with superagi? Thank you.

**Comment by BluePhi09** [comment]
You can now just use Ollama Openai compatible API
