### ISSUE TITLE
One question and one suggestion

### ISSUE THREAD

**Issue by mberman84** [TransformerOptimus/SuperAGI#155]
Do I need the search engine ID if I plan to use Google search? I created a google cloud account, got the API key, but it is returning nothing:

Tool GoogleSearch returned: [{'title': '', 'body': '', 'link': ''}, {'title': '', 'body': '', 'link': ''}, {'title': '', 'body': '', 'link': ''}]

What am I doing wrong?

Suggestion: make the action bar at the top (run, pause, etc) stick at the top when scrolling down.

**Comment by COLONAYUSH** [comment]
Yes, You have to provide a custom serach engine ID if you want search functionality now. you can acquire it from [here](https://programmablesearchengine.google.com/controlpanel/create)
We are planning to integrate serper based searching too, where you will need only one API key to access google.

**Comment by neelayan7** [comment]
Closing this as this is solved.
