### ISSUE TITLE
Troubleshooting PostgreSQL Connection Error

### ISSUE THREAD

**Issue by sambickeita** [TransformerOptimus/SuperAGI#172]
Hello, 

I want to express my gratitude to the SUPERAGI development team for their continuous efforts in providing us with such a valuable project.

I would like to address an error that some of you might encounter when trying to connect to PostgreSQL : 

(SUPER_AGI) PS I:\TEST\SUPER_AGI\SuperAGI-main> i:\TEST\SUPER_AGI\SuperAGI-main\run.bat
Checking if config.yaml file exists...
Checking if virtual environment is activated...
Virtual environment is already activated.      
Checking requirements...
Installing requirements...
Running test.py with python...
Unable to connect to the database: (psycopg2.OperationalError) connection to server on socket "@super__postgres/.s.PGSQL.5432" failed: Invalid argument (0x00002726/10022)
        Is the server running locally and accepting connections on that socket?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "I:\programmes\python\Lib\site-packages\virtualenv\SUPER_AGI\Lib\site-packages\sqlalchemy\engine\base.py", line 3366, in _wrap_pool_connect
    return fn()
           ^^^^
  File "I:\programmes\python\Lib\site-packages\virtualenv\SUPER_AGI\Lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Has anyone encountered this type of error during the initial launch of SuperAGI? If so, how did you configure Postgres to resolve this error?

NB: I am VISUAL STUDIO CODE, and running SuperAGI on local

**Comment by Fluder-Paradyne** [comment]
this is happening because the postgres is not exposed outside the docker

you can run this inside backend container

**Comment by Fluder-Paradyne** [comment]
and cli needs some change to make it work outside docker 
we are working towards it , but our main focus is running it from UI
so try out the UI, you should be able to do everything the current cli support


if you are in windows and postgers container doesn't start 
run the `docker compose up` 
in powershell as admin
