### ISSUE TITLE
some bug in the message life time

### ISSUE THREAD

**Issue by seczoid** [TransformerOptimus/SuperAGI#185]
it will how the message was produced 6 hours ago even though it was produced a minute ago. https://i.imgur.com/JCSb9Mx.png

**Comment by merlinfrombelgium** [comment]
![image](https://github.com/TransformerOptimus/SuperAGI/assets/26247323/e1e70d6c-8dfc-4a11-ae78-b264997ba1fe)
Same here, but it says 2 hours. I'm on UTC+2 time and I'm guessing that's what it's referring to.

**Comment by neelayan7** [comment]
Releasing a fix for this today.

**Comment by neelayan7** [comment]
This is solved.
