### ISSUE TITLE
Support for additional vector databases as LTM

### ISSUE THREAD

**Issue by rico-ocepek** [TransformerOptimus/SuperAGI#186]
Thank you for the project, it works great so far! :)

One thing I was wondering while setting up the project was why Pinecone is the vector DB of choice here.

I have zero knowledge about vector DBs and so it seems odd to me that Pinecone is used here as a default as it only supports 1 index in free tier and rapidly rises to 70$ / month for more indicies which might throw off some potential users of this project. There seem to be open source options out there that could even be integrated into the docker-compose setup. For example [Milvus](https://github.com/milvus-io/milvus).

The code also looks ready to support different databases.

As I said I have zero experience with vector DBs, so please excuse me if I'm asking dumb questions.
Regardless, my questions are:

1. Why did you choose Pinecone?
2. Would Milvus work for the use case?
3. Would the integration really be as simple as implementing a `Milvus` class with two methods just like the `vector_store/Pinecone` class and adding support for it in the `VectorFactory`? (and supply the desired DB driver from all usages of the `VectorFactory`)
4. Wouldn't it make sense to use an open source DB as the default to be easier to set up for new users? 

Thanks for your answer!

**Comment by rico-ocepek** [comment]
Also as far as I can tell this is a duplicate of https://github.com/TransformerOptimus/SuperAGI/issues/3 but I chose to open a new issue to be able to name it more concisely and include some additional info.

**Comment by rico-ocepek** [comment]
Alright that sounds promising!

If Redis is an option that means that LTM really just is a key-value-store and the vector DB just happens to be a more performant key-value-store for this use-case, right?

**Comment by TransformerOptimus** [comment]
We have added vector databases like Pinecone, Redis, Qdrant, Chroma, etc.

**Comment by rico-ocepek** [comment]
Thanks a ton, will test it asap!
