### ISSUE TITLE
[Bug]: Incorrect calculation of duration

### ISSUE THREAD

**Issue by raviwarrier** [TransformerOptimus/SuperAGI#194]
Have a look at the snip:

![image](https://github.com/TransformerOptimus/SuperAGI/assets/42061703/035364f4-13fb-4d11-85c8-ca5bb6f3baa2)

It's not detecting the correct time for the current timezone (somewhere around 11:38a IST) and it reports the conversation to have happened a few hours prior.

**Comment by luciferlinx101** [comment]
Hey guys @raviwarrier @j4acks0n It is a known bug at our end that would be resolved in the next update.

**Comment by birchcode** [comment]
> Hey guys @raviwarrier @j4acks0n It is a known bug at our end that would be resolved in the next update.

Awesome. Does it affect functionality at the moment or just makes it visually confusing?

**Comment by raviwarrier** [comment]
Neither. Just thought I'd bring it to the attention of the devs. :)

**Comment by neelayan7** [comment]
Releasing a fix for this in today's v0.0.7 release.

**Comment by agnes-sharan** [comment]
Hi has then been corrected? I'd like to try it out if not!

**Comment by coder5492** [comment]
@agnes-sharan You can try reproducing the issue and pick it up

**Comment by neelayan7** [comment]
This is solved.
