### ISSUE TITLE
pinecone free plan workaround not clear

### ISSUE THREAD

**Issue by mkmuellner** [TransformerOptimus/SuperAGI#200]
The readme.md says:
"If you're on the Pinecone free plan, you only have 1 pod and 1 index available. As a workaround, change the index name used in test.py where memory is defined: memory = VectorFactory.get_vector_storage("PineCone", "my-current-indexname", OpenAiEmbedding())"

However test.py does not seem to contain a line where memory is defined.
There is a line in the agent_config_values where "memory_window":10 is stated, but that seems different from what the above suggests. Any ideas?

**Comment by CodeManMike** [comment]
Hey dude, I found the line that they are referencing there. its in SuperAGI\SuperAGI\Jobs. 
` try:
                if parsed_config["LTM_DB"] == "Pinecone":
                    memory = VectorFactory.get_vector_storage("PineCone", "super-agent-index1", OpenAiEmbedding())
                else:
                    memory = VectorFactory.get_vector_storage("PineCone", "super-agent-index1", OpenAiEmbedding())
            except:
                print("Unable to setup the pincone connection...")
                memory = None

            user_tools = session.query(Tool).filter(Tool.id.in_(parsed_config["tools"])).all()`

**Comment by mkmuellner** [comment]
Ah thanks! Probably needs an update in the readme.md

**Comment by neelayan7** [comment]
Thanks we'll update this in the readme.md!

**Comment by TsundokuJim** [comment]
> Thanks we'll update this in the readme.md!

It might be worth checking the format of that part of readme.md while you're there. Currently, it displays as a wall of small text, like the legal disclaimers you see on websites that nobody reads. The actual setup instructions are buried among the developer credits. I'm guessing an HTML tag got deleted.

**Comment by luciferlinx101** [comment]
@TsundokuJim Sure we will have a look, you can also raise a PR for the same we can review the same.

**Comment by neelayan7** [comment]
We have solved this issue. Thus closing this.
