### ISSUE TITLE
Tool Write File returned: Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by chrisking1981** [TransformerOptimus/SuperAGI#201]
Tool Write File returned:
Error: [Errno 2] No such file or directory: '/app/workspace/output/workspace/.keep'

I keep getting read/writing errors?

**Comment by h55nick** [comment]
How did you clone the repo?
Can you confirm if the hidden folder `.keep` is in /workspace?
Perhaps your filesystem permissions need to be updated to allow your user to access? (if you aren't root)

**Comment by luciferlinx101** [comment]
Can you check if you have the correct read/write permission, if the issue still persists lets us know.

**Comment by chrisking1981** [comment]
Hi, I did just git clone link from cmd.exe as administrator.
I have the .keep.
Will try playing with permissions! Gosh I didnt even think about that.

Thanks!

**Comment by Agnosaru** [comment]
Thanks, I resolved my issue of SuperAGI not being able to read/write to files by adding "Everyone" will Full Permissions to the "workspace" level folder.

**Comment by neelayan7** [comment]
@chrisking1981 are you still facing this issue in the newer version releases?

**Comment by neelayan7** [comment]
Resolving this issue.
