### ISSUE TITLE
403 bad request

### ISSUE THREAD

**Issue by pedrovily1** [TransformerOptimus/SuperAGI#210]
023-06-06 19:36:45,021: WARNING/ForkPoolWorker-7] Error: 403
superagi-celery-1           | [2023-06-06 19:36:45,023: WARNING/ForkPoolWorker-7] Tool Observation :
superagi-celery-1           | [2023-06-06 19:36:45,023: WARNING/ForkPoolWorker-7] [{'title': '', 'body': '', 'link': ''}, {'title': '', 'body': '', 'link': ''}, {'title': '', 'body': '', 'link': ''}]

every time i try to make a google search i get back this response. And using googleserp tool i only get the first search result text in a summarized version. it is not able to read articles than it starts hallucinating trying to read the articles thinking i have it saved on my system.

**Comment by neelayan7** [comment]
403 can be due to invalid/inaccurate of the Google Search API Key. Can you try generating a new Google Search key and using it again?
Can you elaborate the Google Serp issue with maybe some logs and screenshots?

**Comment by neelayan7** [comment]
@pedrovily1 is this solved?

**Comment by pedrovily1** [comment]
Yes you can close this ticket
