### ISSUE TITLE
Unable to setup Pinecone connection (SSLError: Certificate verify fail in certificate chain)

### ISSUE THREAD

**Issue by Fahmed225** [TransformerOptimus/SuperAGI#212]
I setup and configured all the keys. I hit run and it stays stuck on thinking (even on gpt 3.5 turbo). 

My terminal: 

`
superagi-backend-1          | INFO:     172.19.0.1:47186 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
superagi-celery-1           | [2023-06-07 01:31:15,738: WARNING/ForkPoolWorker-7] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /databases
superagi-celery-1           | [2023-06-07 01:31:16,608: WARNING/ForkPoolWorker-7] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /databases
superagi-celery-1           | [2023-06-07 01:31:17,419: WARNING/ForkPoolWorker-7] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /databases
superagi-celery-1           | [2023-06-07 01:31:18,172: WARNING/ForkPoolWorker-7] Unable to setup the pincone connection...
superagi-celery-1           | [2023-06-07 01:31:18,645: WARNING/ForkPoolWorker-7] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /v1/chat/completions
superagi-celery-1           | [2023-06-07 01:31:18,770: WARNING/ForkPoolWorker-7] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /v1/chat/completions
superagi-celery-1           | [2023-06-07 01:31:18,896: WARNING/ForkPoolWorker-7] Exception:
superagi-celery-1           | [2023-06-07 01:31:18,896: WARNING/ForkPoolWorker-7]  
superagi-celery-1           | [2023-06-07 01:31:18,897: WARNING/ForkPoolWorker-7] Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
superagi-celery-1           | [2023-06-07 01:31:18,897: WARNING/ForkPoolWorker-7] Exception Occured in celery job
superagi-celery-1           | [2023-06-07 01:31:18,897: WARNING/ForkPoolWorker-7] 'content'
superagi-celery-1           | [2023-06-07 01:31:18,938: INFO/ForkPoolWorker-7] Task execute_agent[deace053-5cb0-416c-b515-d29c13241041] succeeded in 5.145790337999642s: None
superagi-backend-1          | INFO:     172.19.0.1:59364 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:59364 - "PUT /agentexecutions/update/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:59364 - "GET /agentexecutions/get/agent/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:59370 - "GET /agents/get/project/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:55084 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:39598 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:40006 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:51878 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.19.0.1:49186 - "GET /agentexecutionfeeds/get/execution/1 HTTP/1.1" 200 OK
`

I start to get 200 OKs but nothing is actually happening. I check pinecone dashboard for activity and there is none. Same with my usage activity in my OpenAI account.

**Comment by FluffLescure** [comment]
I'm having the same issue too, asked about it on discord, apparently backend on docker isn't up yet

**Comment by neelayan7** [comment]
We've removed the default dependency on Pinecone. You can now run SuperAGI without pinecone. Please try that and let us know

**Comment by neelayan7** [comment]
This seems to be an OpenAI related issue. Do make sure your network connection is stable. If it still doesn't work, you can try generating a new OpenAI key, and use that. Do let us know if this works or not.

**Comment by neelayan7** [comment]
@Fahmed225 Is the issue still there?
