### ISSUE TITLE
Docker compiling issues on mac `docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop`

### ISSUE THREAD

**Issue by birchcode** [TransformerOptimus/SuperAGI#215]
Attempting with a fresh install of Docker to `docker-compose up --build` but getting the error: `error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out:`

Docker compose is installed:
```
% docker-compose --version
Docker Compose version v2.18.1
```

I've seen various things around the net about the json config being incorrectly formatted, e.g. credsStore vs credStore:

```
{
        "credsStore": "Desktop",
        "auths": {},
        "credHelpers": {
                "https://index.docker.io/v1/": "desktop"
        },
        "currentContext": "desktop-linux"
}
```

Modifying that line, or removing it entirely makes no difference.

I have also seen recommendations to make sure I'm signed into desktop. I am signed in, and the account is verified.

Any ideas?

**Comment by Fluder-Paradyne** [comment]
try using 
`docker compose`  -- without '-' in between

if it still doesnt work then
check if in your system do you have this file
/.docker/buildx/current

try removing it

**Comment by birchcode** [comment]
Unfortunately I already don't have that file:

```
~/projects/SuperAGI% ls /.docker/buildx/current
ls: /.docker/buildx/current: No such file or directory
```

**Comment by Fluder-Paradyne** [comment]
> > try using `docker compose` -- without '-' in between
> > if it still doesnt work then check if in your system do you have this file /.docker/buildx/current
> > try removing it
> 
> What will removing the file do?

buildx plugin cause some simialr error with my teammates mac
this worked for him so thought it might help

the issue is more to do with setting up docker 
try looking at docker issues

make sure you either have docker-engine or docker desktop only one of these two

**Comment by Rickythegreat1** [comment]
> > > try using `docker compose` -- without '-' in between
> > > if it still doesnt work then check if in your system do you have this file /.docker/buildx/current
> > > try removing it
> > 
> > 
> > What will removing the file do?
> 
> buildx plugin cause some simialr error with my teammates mac this worked for him so thought it might help
> 
> the issue is more to do with setting up docker try looking at docker issues
> 
> make sure you either have docker-engine or docker desktop only one of these two

Why not engine and desktop?

**Comment by birchcode** [comment]
> > > try using `docker compose` -- without '-' in between
> > > if it still doesnt work then check if in your system do you have this file /.docker/buildx/current
> > > try removing it
> > 
> > 
> > What will removing the file do?
> 
> buildx plugin cause some simialr error with my teammates mac this worked for him so thought it might help
> 
> the issue is more to do with setting up docker try looking at docker issues
> 
> make sure you either have docker-engine or docker desktop only one of these two

I removed docker desktop and tried using just docker engine in terminal. I had no success with `docker compose`

**Comment by ClaireCJS** [comment]
I'm in the same boat, but under windows.    Couldn't even find the files you were talking about to remove.

**Comment by ClaireCJS** [comment]
okay for me the problem was i had this folder in my path:
            AddFolderToPathEndOnlyIfItExists "C:\Program Files\Docker\cli-plugins"

but not this one:
            AddFolderToPathEndOnlyIfItExists "C:\Program Files\Docker\Docker\resources\bin"

that fixed the build  for me

**Comment by birchcode** [comment]
I reinstalled docker desktop, did no thing differently I am aware of and the docker-compile worked.
