### ISSUE TITLE
How can I connect to Gmail

### ISSUE THREAD

**Issue by Phoenix2809** [TransformerOptimus/SuperAGI#22]
Hey Guys

I just managed to install SuperAGI and it's working as it should. 

I was thinking of testing a a case where I can write personalized job application emails with my Gmail. Is there any way to connect SuperAGI with gmail?

**Comment by Cptsnowcrasher** [comment]
We are building a tool for connecting Gmail. You can refer the roadmap

**Comment by Cptsnowcrasher** [comment]
It is planned as part of v0.0.2

**Comment by jm789** [comment]
I created a goal for SuperAGI to check my emails for and act upon emails sent from a certain domain. It accesses my gmail mailbox correctly, but appears to read only the first few emails over and over. It can't move on to the older emails lower in the inbox. Is this a bug or am I possibly doing something wrong?

**Comment by TarannJot** [comment]
> I created a goal for SuperAGI to check my emails for and act upon emails sent from a certain domain. It accesses my gmail mailbox correctly, but appears to read only the first few emails over and over. It can't move on to the older emails lower in the inbox. Is this a bug or am I possibly doing something wrong?

Can you let me know the goal that you entered and also the gpt model used.

**Comment by Tarraann** [comment]
> I created a goal for SuperAGI to check my emails for and act upon emails sent from a certain domain. It accesses my gmail mailbox correctly, but appears to read only the first few emails over and over. It can't move on to the older emails lower in the inbox. Is this a bug or am I possibly doing something wrong?

Hi, Can you let me know the agent goal you entered and also gpt model used

**Comment by neelayan7** [comment]
Closing this as this is done.
