### ISSUE TITLE
Use Langchain locally and enable pdf, txt, csv ingestion by implementing localGPT 

### ISSUE THREAD

**Issue by menelic** [TransformerOptimus/SuperAGI#228]
to address #32, #51 and #67 implement  https://github.com/PromtEngineer/localGPT functionality and code as as a tool. this will make SuperAGI more  usable locally.

**Comment by neelayan7** [comment]
We are bringing this functionality soon in the next release. Please stay tuned!

**Comment by neelayan7** [comment]
Tracking this in this PR. https://github.com/TransformerOptimus/SuperAGI/pull/437
