### ISSUE TITLE
No Tools found

### ISSUE THREAD

**Issue by tonishantsms** [TransformerOptimus/SuperAGI#229]
Hello Team,

I am getting error while create the agent on SuperAGI UI - **Add At least one tool**

Below are the logs for the same:
$ docker-compose up --build
[+] Building 8.5s (32/32) FINISHED                                                                               
 => [backend internal] load build definition from Dockerfile                                                0.0s
 => => transferring dockerfile: 377B                                                                        0.0s
 => [backend internal] load .dockerignore                                                                   0.0s
 => => transferring context: 50B                                                                            0.0s
 => [celery internal] load build definition from DockerfileCelery                                           0.0s
 => => transferring dockerfile: 249B                                                                        0.0s
 => [celery internal] load .dockerignore                                                                    0.0s
 => => transferring context: 50B                                                                            0.0s
 => [celery internal] load metadata for docker.io/library/python:3.9                                        0.2s
 => [gui internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 140B                                                                        0.0s
 => [gui internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                             0.0s
 => [gui internal] load metadata for docker.io/library/node:lts                                             0.1s
 => [celery 1/9] FROM docker.io/library/python:3.9@sha256:6e9c45244cf9ef21fe9310f6c7bab754c5e4d23c819421f9  0.0s
 => [backend internal] load build context                                                                   0.1s
 => => transferring context: 166.45kB                                                                       0.1s
 => [celery internal] load build context                                                                    0.1s
 => => transferring context: 166.45kB                                                                       0.1s
 => [gui 1/5] FROM docker.io/library/node:lts@sha256:8cdf7234449f35e579f7491137807ddb3a089f028862f7ab69af4  0.0s
 => [gui internal] load build context                                                                       0.0s
 => => transferring context: 4.48kB                                                                         0.0s
 => CACHED [gui 2/5] WORKDIR /app                                                                           0.0s
 => CACHED [gui 3/5] COPY package*.json ./                                                                  0.0s
 => CACHED [gui 4/5] RUN npm install                                                                        0.0s
 => [gui 5/5] COPY . .                                                                                      0.2s
 => CACHED [celery 2/9] WORKDIR /app                                                                        0.0s
 => CACHED [backend 3/9] COPY requirements.txt .                                                            0.0s
 => CACHED [backend 4/9] RUN pip install --no-cache-dir -r requirements.txt                                 0.0s
 => [backend 5/9] COPY . .                                                                                  0.4s
 => [gui] exporting to image                                                                                0.1s
 => => exporting layers                                                                                     0.0s
 => => writing image sha256:2b6f30bc2078320193e11c2eba9d77c3452b86dbb4b054f7c4d5d689ec85ba39                0.0s
 => => naming to docker.io/library/superagi-gui                                                             0.0s
 => [backend 6/9] COPY config.yaml ./config.yaml                                                            0.1s
 => CACHED [celery 3/6] COPY requirements.txt .                                                             0.0s
 => CACHED [celery 4/6] RUN pip install --no-cache-dir -r requirements.txt                                  0.0s
 => CACHED [celery 5/6] COPY . .                                                                            0.0s
 => [celery 6/6] COPY config.yaml .                                                                         0.1s
 => [backend 7/9] COPY entrypoint.sh /entrypoint.sh                                                         0.1s
 => [celery] exporting to image                                                                             0.2s
 => => exporting layers                                                                                     0.2s
 => => writing image sha256:23e2d36782720209efa7b04bd04ab68ecd0eeef300a6e6e42b027151f80da34c                0.0s
 => => naming to docker.io/library/superagi-celery                                                          0.0s
 => [backend 8/9] COPY wait-for-it.sh /wait-for-it.sh                                                       0.1s
 => [backend 9/9] RUN chmod +x /entrypoint.sh /wait-for-it.sh                                               7.3s
 => [backend] exporting to image                                                                            0.0s
 => => exporting layers                                                                                     0.0s
 => => writing image sha256:219d9f79042a8c87e7b26eeae662ed03b7c1bc7995ce7c399666c8e8081e4dcd                0.0s
 => => naming to docker.io/library/superagi-backend                                                         0.0s
[+] Running 5/5
 ✔ Container superagi-gui-1              Recreated                                                          0.1s 
 ✔ Container superagi-super__postgres-1  Created                                                            0.0s 
 ✔ Container superagi-super__redis-1     Created                                                            0.0s 
 ✔ Container superagi-celery-1           Recreated                                                          0.2s 
 ✔ Container superagi-backend-1          Recreated                                                          0.2s 
Attaching to superagi-backend-1, superagi-celery-1, superagi-gui-1, superagi-super__postgres-1, superagi-super__redis-1
superagi-super__redis-1     | 1:C 07 Jun 2023 12:23:23.672 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superagi-super__redis-1     | 1:C 07 Jun 2023 12:23:23.672 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
superagi-super__redis-1     | 1:C 07 Jun 2023 12:23:23.672 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superagi-super__redis-1     | 1:M 07 Jun 2023 12:23:23.674 * monotonic clock: POSIX clock_gettime
superagi-super__redis-1     | 1:M 07 Jun 2023 12:23:23.680 * Running mode=standalone, port=6379.
superagi-super__redis-1     | 1:M 07 Jun 2023 12:23:23.680 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
superagi-super__redis-1     | 1:M 07 Jun 2023 12:23:23.680 # Server initialized
superagi-super__redis-1     | 1:M 07 Jun 2023 12:23:23.681 * Ready to accept connections
superagi-super__postgres-1  | 
superagi-super__postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 2023-06-07 12:23:23.843 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
superagi-super__postgres-1  | 2023-06-07 12:23:23.845 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superagi-super__postgres-1  | 2023-06-07 12:23:23.845 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superagi-super__postgres-1  | 2023-06-07 12:23:23.849 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-super__postgres-1  | 2023-06-07 12:23:23.855 UTC [30] LOG:  database system was interrupted; last known up at 2023-06-07 12:13:05 UTC
superagi-super__postgres-1  | 2023-06-07 12:23:23.881 UTC [30] LOG:  database system was not properly shut down; automatic recovery in progress
superagi-super__postgres-1  | 2023-06-07 12:23:23.889 UTC [30] LOG:  redo starts at 0/19DAAB8
superagi-super__postgres-1  | 2023-06-07 12:23:23.892 UTC [30] LOG:  invalid record length at 0/19DABA0: wanted 24, got 0
superagi-super__postgres-1  | 2023-06-07 12:23:23.892 UTC [30] LOG:  redo done at 0/19DAB68 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
superagi-super__postgres-1  | 2023-06-07 12:23:23.899 UTC [28] LOG:  checkpoint starting: end-of-recovery immediate wait
superagi-super__postgres-1  | 2023-06-07 12:23:23.911 UTC [28] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.002 s, total=0.015 s; sync files=2, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
superagi-super__postgres-1  | 2023-06-07 12:23:23.917 UTC [1] LOG:  database system is ready to accept connections
superagi-gui-1              | 
superagi-gui-1              | > super-agi@0.1.0 dev
superagi-gui-1              | > next dev
superagi-gui-1              | 
superagi-backend-1          | wait-for-it.sh: waiting 60 seconds for super__postgres:5432
superagi-backend-1          | wait-for-it.sh: super__postgres:5432 is available after 0 seconds
superagi-gui-1              | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
superagi-gui-1              | - warn Invalid next.config.js options detected: 
superagi-gui-1              | - warn     The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, target, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
superagi-gui-1              | - warn See more info here: https://nextjs.org/docs/messages/invalid-next-config
superagi-backend-1          | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
superagi-backend-1          | INFO  [alembic.runtime.migration] Will assume transactional DDL.
superagi-backend-1          | INFO:     Will watch for changes in these directories: ['/app']
superagi-backend-1          | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
superagi-backend-1          | INFO:     Started reloader process [1] using WatchFiles
superagi-celery-1           | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-backend-1          | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-celery-1           | /usr/local/lib/python3.9/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
superagi-celery-1           | absolutely not recommended!
superagi-celery-1           | 
superagi-celery-1           | Please specify a different user using the --uid option.
superagi-celery-1           | 
superagi-celery-1           | User information: uid=0 euid=0 gid=0 egid=0
superagi-celery-1           | 
superagi-celery-1           |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
superagi-celery-1           |  
superagi-celery-1           |  -------------- celery@d0395fb86ae9 v5.2.7 (dawn-chorus)
superagi-celery-1           | --- ***** ----- 
superagi-celery-1           | -- ******* ---- Linux-4.4.0-210-generic-x86_64-with-glibc2.31 2023-06-07 12:23:31
superagi-celery-1           | - *** --- * --- 
superagi-celery-1           | - ** ---------- [config]
superagi-celery-1           | - ** ---------- .> app:         superagi:0x7f0aeb35b2e0
superagi-celery-1           | - ** ---------- .> transport:   redis://super__redis:6379/0
superagi-celery-1           | - ** ---------- .> results:     redis://super__redis:6379/0
superagi-celery-1           | - *** --- * --- .> concurrency: 10 (prefork)
superagi-celery-1           | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
superagi-celery-1           | --- ***** ----- 
superagi-celery-1           |  -------------- [queues]
superagi-celery-1           |                 .> celery           exchange=celery(direct) key=celery
superagi-celery-1           |                 
superagi-celery-1           | 
superagi-celery-1           | [tasks]
superagi-celery-1           |   . execute_agent
superagi-celery-1           | 
superagi-backend-1          | INFO:     Started server process [20]
superagi-backend-1          | INFO:     Waiting for application startup.
superagi-backend-1          | INFO:     Application startup complete.
superagi-celery-1           | [2023-06-07 12:23:33,738: INFO/MainProcess] Connected to redis://super__redis:6379/0
superagi-celery-1           | [2023-06-07 12:23:33,754: INFO/MainProcess] mingle: searching for neighbors
superagi-celery-1           | [2023-06-07 12:23:34,794: INFO/MainProcess] mingle: all alone
superagi-celery-1           | [2023-06-07 12:23:34,842: INFO/MainProcess] celery@d0395fb86ae9 ready.
superagi-gui-1              | - event compiled client and server successfully in 5s (775 modules)
superagi-gui-1              | - wait compiling...
superagi-gui-1              | - event compiled client and server successfully in 1625 ms (775 modules)
superagi-gui-1              | - wait compiling /_error (client and server)...
superagi-gui-1              | - event compiled client and server successfully in 640 ms (776 modules)
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead. 
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component

Can you please help

**Comment by TransformerOptimus** [comment]
Can you pull latest main branch and run `docker compose up --build`. We have added certain fixes for the new installation.

**Comment by tonishantsms** [comment]
@TransformerOptimus  After pulled the latest changes, Super AGI UI is Initializing stage. Not getting dashboard view

$ docker compose up --build
[+] Building 0.3s (32/32) FINISHED                                                                               
 => [backend internal] load build definition from Dockerfile                                                0.0s
 => => transferring dockerfile: 377B                                                                        0.0s
 => [backend internal] load .dockerignore                                                                   0.0s
 => => transferring context: 50B                                                                            0.0s
 => [gui internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 140B                                                                        0.0s
 => [gui internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                             0.0s
 => [celery internal] load build definition from DockerfileCelery                                           0.0s
 => => transferring dockerfile: 249B                                                                        0.0s
 => [celery internal] load .dockerignore                                                                    0.0s
 => => transferring context: 50B                                                                            0.0s
 => [backend internal] load metadata for docker.io/library/python:3.9                                       0.1s
 => [gui internal] load metadata for docker.io/library/node:lts                                             0.1s
 => [gui 1/5] FROM docker.io/library/node:lts@sha256:8cdf7234449f35e579f7491137807ddb3a089f028862f7ab69af4  0.0s
 => [gui internal] load build context                                                                       0.0s
 => => transferring context: 4.68kB                                                                         0.0s
 => [backend 1/6] FROM docker.io/library/python:3.9@sha256:6e9c45244cf9ef21fe9310f6c7bab754c5e4d23c819421f  0.0s
 => [celery internal] load build context                                                                    0.0s
 => => transferring context: 20.12kB                                                                        0.0s
 => [backend internal] load build context                                                                   0.0s
 => => transferring context: 20.12kB                                                                        0.0s
 => CACHED [gui 2/5] WORKDIR /app                                                                           0.0s
 => CACHED [gui 3/5] COPY package*.json ./                                                                  0.0s
 => CACHED [gui 4/5] RUN npm install                                                                        0.0s
 => CACHED [gui 5/5] COPY . .                                                                               0.0s
 => [gui] exporting to image                                                                                0.0s
 => => exporting layers                                                                                     0.0s
 => => writing image sha256:23477519d2b1426643f4771917fb30df5ac235c5d578cf230fb679b2648ca607                0.0s
 => => naming to docker.io/library/superagi-gui                                                             0.0s
 => CACHED [celery 2/6] WORKDIR /app                                                                        0.0s
 => CACHED [backend 3/9] COPY requirements.txt .                                                            0.0s
 => CACHED [backend 4/9] RUN pip install --no-cache-dir -r requirements.txt                                 0.0s
 => CACHED [backend 5/9] COPY . .                                                                           0.0s
 => CACHED [backend 6/9] COPY config.yaml ./config.yaml                                                     0.0s
 => CACHED [backend 7/9] COPY entrypoint.sh /entrypoint.sh                                                  0.0s
 => CACHED [backend 8/9] COPY wait-for-it.sh /wait-for-it.sh                                                0.0s
 => CACHED [backend 9/9] RUN chmod +x /entrypoint.sh /wait-for-it.sh                                        0.0s
 => CACHED [celery 3/6] COPY requirements.txt .                                                             0.0s
 => CACHED [celery 4/6] RUN pip install --no-cache-dir -r requirements.txt                                  0.0s
 => CACHED [celery 5/6] COPY . .                                                                            0.0s
 => CACHED [celery 6/6] COPY config.yaml .                                                                  0.0s
 => [celery] exporting to image                                                                             0.0s
 => => exporting layers                                                                                     0.0s
 => => writing image sha256:346b051d6e21b683906b7a54398c379505d11e6a9d2621de1c4c3afbce6f55bd                0.0s
 => => naming to docker.io/library/superagi-celery                                                          0.0s
 => [backend] exporting to image                                                                            0.0s
 => => exporting layers                                                                                     0.0s
 => => writing image sha256:69dba2007618a29f307d44e561cf221470d4f49b70f92392939fe7f8d58fc631                0.0s
 => => naming to docker.io/library/superagi-backend                                                         0.0s
[+] Running 5/0
 ✔ Container superagi-super__postgres-1  Created                                                            0.0s 
 ✔ Container superagi-gui-1              Created                                                            0.0s 
 ✔ Container superagi-super__redis-1     Created                                                            0.0s 
 ✔ Container superagi-backend-1          Created                                                            0.0s 
 ✔ Container superagi-celery-1           Created                                                            0.0s 
Attaching to superagi-backend-1, superagi-celery-1, superagi-gui-1, superagi-super__postgres-1, superagi-super__redis-1
superagi-super__redis-1     | 1:C 08 Jun 2023 07:08:24.721 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superagi-super__redis-1     | 1:C 08 Jun 2023 07:08:24.721 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
superagi-super__redis-1     | 1:C 08 Jun 2023 07:08:24.721 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superagi-super__redis-1     | 1:M 08 Jun 2023 07:08:24.722 * monotonic clock: POSIX clock_gettime
superagi-super__redis-1     | 1:M 08 Jun 2023 07:08:24.723 * Running mode=standalone, port=6379.
superagi-super__redis-1     | 1:M 08 Jun 2023 07:08:24.724 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
superagi-super__redis-1     | 1:M 08 Jun 2023 07:08:24.724 # Server initialized
superagi-super__redis-1     | 1:M 08 Jun 2023 07:08:24.730 * Ready to accept connections
superagi-super__postgres-1  | 
superagi-super__postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 2023-06-08 07:08:24.883 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
superagi-super__postgres-1  | 2023-06-08 07:08:24.883 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superagi-super__postgres-1  | 2023-06-08 07:08:24.884 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superagi-super__postgres-1  | 2023-06-08 07:08:24.887 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-super__postgres-1  | 2023-06-08 07:08:24.893 UTC [29] LOG:  database system was interrupted; last known up at 2023-06-08 06:41:17 UTC
superagi-super__postgres-1  | 2023-06-08 07:08:24.910 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
superagi-super__postgres-1  | 2023-06-08 07:08:24.912 UTC [29] LOG:  redo starts at 0/19FEF30
superagi-super__postgres-1  | 2023-06-08 07:08:24.912 UTC [29] LOG:  invalid record length at 0/19FF018: wanted 24, got 0
superagi-super__postgres-1  | 2023-06-08 07:08:24.912 UTC [29] LOG:  redo done at 0/19FEFE0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
superagi-super__postgres-1  | 2023-06-08 07:08:24.916 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
superagi-super__postgres-1  | 2023-06-08 07:08:24.920 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.005 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
superagi-super__postgres-1  | 2023-06-08 07:08:24.924 UTC [1] LOG:  database system is ready to accept connections
superagi-backend-1          | wait-for-it.sh: waiting 60 seconds for super__postgres:5432
superagi-backend-1          | wait-for-it.sh: super__postgres:5432 is available after 0 seconds
superagi-gui-1              | 
superagi-gui-1              | > super-agi@0.1.0 dev
superagi-gui-1              | > next dev
superagi-gui-1              | 
superagi-gui-1              | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
superagi-backend-1          | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
superagi-backend-1          | INFO  [alembic.runtime.migration] Will assume transactional DDL.
superagi-backend-1          | INFO:     Will watch for changes in these directories: ['/app']
superagi-backend-1          | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
superagi-backend-1          | INFO:     Started reloader process [1] using WatchFiles
superagi-gui-1              | - warn Invalid next.config.js options detected: 
superagi-gui-1              | - warn     The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, target, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
superagi-gui-1              | - warn See more info here: https://nextjs.org/docs/messages/invalid-next-config
superagi-celery-1           | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-backend-1          | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-celery-1           | /usr/local/lib/python3.9/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
superagi-celery-1           | absolutely not recommended!
superagi-celery-1           | 
superagi-celery-1           | Please specify a different user using the --uid option.
superagi-celery-1           | 
superagi-celery-1           | User information: uid=0 euid=0 gid=0 egid=0
superagi-celery-1           | 
superagi-celery-1           |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
superagi-celery-1           |  
superagi-celery-1           |  -------------- celery@91d6fb64e2b2 v5.2.7 (dawn-chorus)
superagi-celery-1           | --- ***** ----- 
superagi-celery-1           | -- ******* ---- Linux-4.4.0-210-generic-x86_64-with-glibc2.31 2023-06-08 07:08:28
superagi-celery-1           | - *** --- * --- 
superagi-celery-1           | - ** ---------- [config]
superagi-celery-1           | - ** ---------- .> app:         superagi:0x7f1d9f3d8be0
superagi-celery-1           | - ** ---------- .> transport:   redis://super__redis:6379/0
superagi-celery-1           | - ** ---------- .> results:     redis://super__redis:6379/0
superagi-celery-1           | - *** --- * --- .> concurrency: 10 (prefork)
superagi-celery-1           | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
superagi-celery-1           | --- ***** ----- 
superagi-celery-1           |  -------------- [queues]
superagi-celery-1           |                 .> celery           exchange=celery(direct) key=celery
superagi-celery-1           |                 
superagi-celery-1           | 
superagi-celery-1           | [tasks]
superagi-celery-1           |   . execute_agent
superagi-celery-1           | 
superagi-backend-1          | INFO:     Started server process [20]
superagi-backend-1          | INFO:     Waiting for application startup.
superagi-backend-1          | INFO:     Application startup complete.
superagi-celery-1           | [2023-06-08 07:08:30,803: INFO/MainProcess] Connected to redis://super__redis:6379/0
superagi-celery-1           | [2023-06-08 07:08:30,812: INFO/MainProcess] mingle: searching for neighbors
superagi-celery-1           | [2023-06-08 07:08:31,836: INFO/MainProcess] mingle: all alone
superagi-celery-1           | [2023-06-08 07:08:31,855: INFO/MainProcess] celery@91d6fb64e2b2 ready.
superagi-gui-1              | - event compiled client and server successfully in 2.9s (781 modules)
superagi-gui-1              | - wait compiling...
superagi-gui-1              | - event compiled client and server successfully in 946 ms (781 modules)
superagi-gui-1              | - wait compiling /_error (client and server)...
superagi-gui-1              | - event compiled client and server successfully in 293 ms (782 modules)
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap"). Use Document instead. 
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead. 
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-gui-1              | - wait compiling /favicon.ico/route (client and server)...
superagi-gui-1              | - event compiled successfully in 930 ms (135 modules)

**Comment by DOGECOIN87** [comment]
I get the same result, I followed every detail exactly for installation, but I cannot add any tools via the GUI... etc

**Comment by neelayan7** [comment]
@DOGECOIN87 is the issue persisting even now? With the newer version release, this problem shouldn't arise.

**Comment by neelayan7** [comment]
Resolving this as this is solved in the newer versions!
