### ISSUE TITLE
Add at least one tool error

### ISSUE THREAD

**Issue by Kashif-Raza6** [TransformerOptimus/SuperAGI#234]
Added tools as shown in the image but still getting the error
![image](https://github.com/TransformerOptimus/SuperAGI/assets/96944736/02fbd00c-5437-49d6-bfc3-0f7d340e8bfe)

**Comment by linus-nicole** [comment]
yes,i met too

**Comment by linus-nicole** [comment]
yes, same problem

**Comment by Kashif-Raza6** [comment]
repo updated and now its working fine.
