### ISSUE TITLE
Won't load - was working fine

### ISSUE THREAD

**Issue by NeVeREire** [TransformerOptimus/SuperAGI#239]
I had it all working and had agents running testing out some things. 
I left it for a few hours doing nothing, and when I came back the UI was frozen or sorts, Refreshing the page did nothing. 

I checked docker and it was still running. 

I stopped docker and closed the UI, 
I restarted docker using terminal inside VCS by entering docker-compose up --build it ran through the code and everything looked fine, but localhost:3000 won't load, I tried stopping and starting many times... It just won't load. 

Any ideas? or anywhere I can see an error log or something?

**Comment by shoptacle** [comment]
@NeVeREire are you seeing any errors in docker logs? It's also not running for me, as I described in #269

**Comment by luciferlinx101** [comment]
@NeVeREire can you share the logs please?

**Comment by neelayan7** [comment]
@NeVeREire is the issue resolved with the newer version releases?

**Comment by neelayan7** [comment]
This seems to have solved with the newer version releases. Closing this.
