### ISSUE TITLE
Twitter Bot with SuperAGI

### ISSUE THREAD

**Issue by Phoenix2809** [TransformerOptimus/SuperAGI#24]
I'm trying to connect SuperAGI to Twitter so that the agent can scout for the latest trends in AI, summarize that and create automated tweets with the summary. Is there any way to connect Twitter?

**Comment by neelayan7** [comment]
This is part of the roadmap and will be going live in v0.0.7 scheduled for today!

**Comment by neelayan7** [comment]
We have created a Twitter Tool.
