### ISSUE TITLE
LocalAI integration: Run with local models

### ISSUE THREAD

**Issue by mudler** [TransformerOptimus/SuperAGI#247]
Great project!

Did you considered the possibility to run models locally? There are projects like LocalAI https://github.com/go-skynet/LocalAI that provide a free, drop-in OpenAI alternative with local models.

I think also #243 is tangentially related, as could be leveraged to use LocalAI instead of OpenAI

**Comment by sirajperson** [comment]
I created a pull request adding it. [PR](https://github.com/TransformerOptimus/SuperAGI/issues/247). Full discussion in issue [#243](https://github.com/TransformerOptimus/SuperAGI/issues/243)

**Comment by neelayan7** [comment]
Closing this as we have merged @sirajperson 's PR https://github.com/TransformerOptimus/SuperAGI/pull/289

**Comment by neelayan7** [comment]
Closing this as this is solved.
