### ISSUE TITLE
Basically all tools give Error generating text: 'content'

### ISSUE THREAD

**Issue by cranyy** [TransformerOptimus/SuperAGI#249]
Just pulled the new version to see the changes and they look great. however, the tools seem to be broken.

I keep getting this error for almost all tools that are used:

Tool CodingTool returned: Error generating text: 'content'
Tool ThinkingTool returned: Error generating text: 'content'
Tool GoogleSearch returned: Error1: 'content', KeyError, args: {'query': 'always sunny release date'}
Tool GoogleSerp returned: Error1: 'content', KeyError, args: {'query': 'always sunny release date'}

**Comment by TransformerOptimus** [comment]
Can you paste the docker logs here? Error seem to be related to the openai api call.

**Comment by cranyy** [comment]
It seems to always request more than my api key can handle (8192). This is after i asked for a simple blackjack script in python.    
   
   
   
      | INFO:     172.18.0.1:37590 - "GET /agentexecutionfeeds/get/execution/9 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.18.0.1:37908 - "GET /agentexecutionfeeds/get/execution/9 HTTP/1.1" 200 OK
superagi-super__redis-1     | 1:M 08 Jun 2023 11:33:51.767 * 100 changes in 300 seconds. Saving...
superagi-super__redis-1     | 1:M 08 Jun 2023 11:33:51.768 * Background saving started by pid 20
superagi-super__redis-1     | 20:C 08 Jun 2023 11:33:51.772 * DB saved on disk
superagi-super__redis-1     | 20:C 08 Jun 2023 11:33:51.773 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
superagi-super__redis-1     | 1:M 08 Jun 2023 11:33:51.869 * Background saving terminated with success
superagi-backend-1          | INFO:     172.18.0.1:33670 - "GET /agentexecutionfeeds/get/execution/9 HTTP/1.1" 200 OK
superagi-celery-1           | [2023-06-08 11:34:04,353: WARNING/ForkPoolWorker-7] {
superagi-celery-1           |     "thoughts": {
superagi-celery-1           |         "text": "I need to write a simple blackjack script in Python.",
superagi-celery-1           |         "reasoning": "To accomplish this task, I need to first understand the rules and basic strategy for a simple blackjack game.",
superagi-celery-1           |         "plan": "- Use GoogleSearch to find information on simple blackjack rules and strategies\n- Write the Python script for a simple blackjack game",
superagi-celery-1           |         "criticism": "I should ensure that I understand the rules and strategies for a simple blackjack game before proceeding with writing the script.",
superagi-celery-1           |         "speak": "I will search for information on simple blackjack rules and strategies, and then write a Python script for the game."
superagi-celery-1           |     },
superagi-celery-1           |     "tool": {
superagi-celery-1           |         "name": "GoogleSearch",
superagi-celery-1           |         "description": "A tool for performing a Google search and extracting snippets and webpages. Input should be a search query.",
superagi-celery-1           |         "args": {
superagi-celery-1           |             "query": "simple blackjack rules and strategies"
superagi-celery-1           |         }
superagi-celery-1           |     }
superagi-celery-1           | }
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Intelligence :
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Thoughts: I need to write a simple blackjack script in Python.
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Reasoning: To accomplish this task, I need to first understand the rules and basic strategy for a simple blackjack game.
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Plan: - Use GoogleSearch to find information on simple blackjack rules and strategies- Write the Python script for a simple blackjack game
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Criticism: I should ensure that I understand the rules and strategies for a simple blackjack game before proceeding with writing the script.
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Action :
superagi-celery-1           | [2023-06-08 11:34:04,354: WARNING/ForkPoolWorker-7] Tool: GoogleSearch
superagi-celery-1           | [2023-06-08 11:34:04,460: WARNING/ForkPoolWorker-7] Error: 400
superagi-celery-1           | [2023-06-08 11:34:04,462: WARNING/ForkPoolWorker-7] Google blocked the request. Trying again...
superagi-backend-1          | INFO:     172.18.0.1:34584 - "GET /agentexecutionfeeds/get/execution/9 HTTP/1.1" 200 OK
superagi-celery-1           | [2023-06-08 11:34:07,567: WARNING/ForkPoolWorker-7] Error: 400
superagi-celery-1           | [2023-06-08 11:34:07,569: WARNING/ForkPoolWorker-7] Google blocked the request. Trying again...
superagi-celery-1           | [2023-06-08 11:34:10,672: WARNING/ForkPoolWorker-7] Error: 400
superagi-celery-1           | [2023-06-08 11:34:10,960: INFO/ForkPoolWorker-7] error_code=context_length_exceeded error_message="This model's maximum context length is 8192 tokens. However, you requested 8247 tokens (55 in the messages, 8192 in the completion). Please reduce the length of the messages or completion." error_param=messages error_type=invalid_request_error message='OpenAI API error received' stream_error=False
superagi-celery-1           | [2023-06-08 11:34:10,960: WARNING/ForkPoolWorker-7] Exception:
superagi-celery-1           | [2023-06-08 11:34:10,961: WARNING/ForkPoolWorker-7]
superagi-celery-1           | [2023-06-08 11:34:10,961: WARNING/ForkPoolWorker-7] This model's maximum context length is 8192 tokens. However, you requested 8247 tokens (55 in the messages, 8192 in the completion). Please reduce the length of the messages or completion.
superagi-celery-1           | [2023-06-08 11:34:10,961: WARNING/ForkPoolWorker-7] Tool Response : {'result': "Tool GoogleSearch returned: Error1: 'content', KeyError, args: {'query': 'simple blackjack rules and strategies'}", 'retry': False}
superagi-celery-1           | [2023-06-08 11:34:10,975: WARNING/ForkPoolWorker-7] Iteration completed moving to next iteration!
superagi-celery-1           | [2023-06-08 11:34:10,977: WARNING/ForkPoolWorker-7] Starting next job for agent execution id:
superagi-celery-1           | [2023-06-08 11:34:10,977: WARNING/ForkPoolWorker-7]
superagi-celery-1           | [2023-06-08 11:34:10,977: WARNING/ForkPoolWorker-7] 9
superagi-celery-1           | [2023-06-08 11:34:10,980: INFO/MainProcess] Task execute_agent[b4fdc2ba-80df-45a7-91eb-6da95062a374] received
superagi-celery-1           | [2023-06-08 11:34:10,981: INFO/ForkPoolWorker-7] Task execute_agent[53aa7381-ce68-4e75-b3fc-0c85c8cff125] succeeded in 41.25031573700005s: None
superagi-celery-1           | [2023-06-08 11:34:10,981: WARNING/ForkPoolWorker-8] Execute agent:2023-06-08T11:34:10.977529,9
superagi-celery-1           | [2023-06-08 11:34:13,342: WARNING/ForkPoolWorker-8] You are SuperAGI an AI assistant to solve complex problems. Your decisions must always be made independently without seeking user assistance.
superagi-celery-1           |  Play to your strengths as an LLM and pursue simple strategies with no legal complications.


------


ragi-celery-1           |     }
superagi-celery-1           | }
superagi-celery-1           | [2023-06-08 11:35:15,173: WARNING/ForkPoolWorker-7] Intelligence :
superagi-celery-1           | [2023-06-08 11:35:15,173: WARNING/ForkPoolWorker-7] Thoughts: I have gathered information on simple blackjack rules. Now, I need to write the Python script.
superagi-celery-1           | [2023-06-08 11:35:15,173: WARNING/ForkPoolWorker-7] Reasoning: I will use the information I've gathered to write a simple blackjack script in Python, keeping in mind the rules and strategies.
superagi-celery-1           | [2023-06-08 11:35:15,173: WARNING/ForkPoolWorker-7] Plan: - Write the Python script for a simple blackjack game
superagi-celery-1           | [2023-06-08 11:35:15,173: WARNING/ForkPoolWorker-7] Criticism: I should ensure that the script follows the rules and strategies for a simple blackjack game and is well-structured.
superagi-celery-1           | [2023-06-08 11:35:15,174: WARNING/ForkPoolWorker-7] Action :
superagi-celery-1           | [2023-06-08 11:35:15,174: WARNING/ForkPoolWorker-7] Tool: CodingTool
superagi-celery-1           | [2023-06-08 11:35:15,470: INFO/ForkPoolWorker-7] error_code=context_length_exceeded error_message="This model's maximum context length is 8192 tokens. However, you requested 8313 tokens (121 in the messages, 8192 in the completion). Please reduce the length of the messages or completion." error_param=messages error_type=invalid_request_error message='OpenAI API error received' stream_error=False
superagi-celery-1           | [2023-06-08 11:35:15,470: WARNING/ForkPoolWorker-7] Exception:
superagi-celery-1           | [2023-06-08 11:35:15,470: WARNING/ForkPoolWorker-7]
superagi-celery-1           | [2023-06-08 11:35:15,470: WARNING/ForkPoolWorker-7] This model's maximum context length is 8192 tokens. However, you requested 8313 tokens (121 in the messages, 8192 in the completion). Please reduce the length of the messages or completion.
superagi-celery-1           | [2023-06-08 11:35:15,470: WARNING/ForkPoolWorker-7] 'content'
superagi-celery-1           | [2023-06-08 11:35:15,471: WARNING/ForkPoolWorker-7] Tool Observation :
superagi-celery-1           | [2023-06-08 11:35:15,471: WARNING/ForkPoolWorker-7] Error generating text: 'content'
superagi-celery-1           | [2023-06-08 11:35:15,471: WARNING/ForkPoolWorker-7] Tool Response : {'result': "Tool CodingTool returned: Error generating text: 'content'", 'retry': False}
superagi-celery-1           | [2023-06-08 11:35:15,475: WARNING/ForkPoolWorker-7] Iteration completed moving to next iteration!
superagi-celery-1           | [2023-06-08 11:35:15,476: WARNING/ForkPoolWorker-7] Starting next job for agent execution id:
superagi-celery-1           | [2023-06-08 11:35:15,476: WARNING/ForkPoolWorker-7]
superagi-celery-1           | [2023-06-08 11:35:15,476: WARNING/ForkPoolWorker-7] 9
superagi-celery-1           | [2023-06-08 11:35:15,478: INFO/MainProcess] Task execute_agent[1dde79b2-c3b5-4083-aeac-1f6f186232da] received
superagi-celery-1           | [2023-06-08 11:35:15,479: INFO/ForkPoolWorker-7] Task execute_agent[f36e9c84-4d36-42ea-8873-b408601c0f60] succeeded in 28.40088622499991s: None
superagi-celery-1           | [2023-06-08 11:35:15,479: WARNING/ForkPoolWorker-8] Execute agent:2023-06-08T11:35:15.476381,9
superagi-celery-1           | [2023-06-08 11:35:15,487: INFO/ForkPoolWorker-8] Task execute_agent[1dde79b2-c3b5-4083-aeac-1f6f186232da] succeeded in 0.007651591000012559s: None
superagi-backend-1          | INFO:     172.18.0.1:56600 - "GET /agentexecutionfeeds/get/execution/9 HTTP/1.1" 200 OK
superagi-super__postgres-1  | 2023-06-08 11:35:34.187 UTC [27] LOG:  checkpoint starting: time
superagi-super__postgres-1  | 2023-06-08 11:35:35.009 UTC [27] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.803 s, sync=0.015 s, total=0.822 s; sync files=6, longest=0.014 s, average=0.003 s; distance=42 kB, estimate=47 kB

**Comment by justquick** [comment]
Im getting this one too. What I think is happening is agi is trying to submit a request (or getting a response) that is too large for my OpenAI GPT3.5turbo personal subscription plan to process. Im sure if I paid OpenAI more I could shove more tokens through it but this is a real world, hard limit for most folks just starting out with this tool (i bought a subscription just to play w/ this tool)

```
This model's maximum context length is 4097 tokens. However, your messages resulted in 14057 tokens. Please reduce the length of the messages.
superagi-celery-1           | [2023-06-08 17:22:45,907: WARNING/ForkPoolWorker-8] Tool Response : {'result': "Tool GoogleSearch returned: Error1: 'content', KeyError, args: {'query': 'building a QA chatbot with GPT-4 scholarly articles site:arxiv.org'}", 'retry': False}
```

**Comment by neelayan7** [comment]
@cranyy is this issue still persisting with the latest version releases?

**Comment by neelayan7** [comment]
Closing this issue as this is solved in the latest versions.

**Comment by darrenkras** [comment]
i am getting this error on the cloud version. i tried running the coding agent as per the template and get this error.

Tool WriteSpecTool returned: Error1: 'content', KeyError, args: {'task_description': 'Write a specification for a browser-based Pomodoro App. The app should have a timer that can be set to 25 minutes for work sessions and 5 minutes for breaks. It should also have start, pause, and reset buttons.', 'spec_file_name': 'pomodoro_app_spec.txt'}

the error happens multiple times before the agent gives up.

**Comment by teretz** [comment]
i get this as well.
