### ISSUE TITLE
lag while sliding the "create agent" page

### ISSUE THREAD

**Issue by Mingzefei** [TransformerOptimus/SuperAGI#262]
I experience lag while sliding the "create agent" page, and it takes several minutes before I can slide up and down again. 

Has anyone encountered a similar situation?

**Comment by neelayan7** [comment]
Can you retry this again and check? Is this happening everytime?

**Comment by Mingzefei** [comment]
It happends afterI click the "show advanced options", almost every time.

**Comment by neelayan7** [comment]
@Mingzefei this issue shouldn't arise with the latest releases. Can you check again?

**Comment by Mingzefei** [comment]
yes, I don't feel any lag now.
Thanks!

**Comment by neelayan7** [comment]
Awesome. Closing this issue. Do let me know if you face any other issue.
