### ISSUE TITLE
Human tool throws EOF error and doesn't request for input

### ISSUE THREAD

**Issue by merlinfrombelgium** [TransformerOptimus/SuperAGI#266]
`Tool Human returned: Error1: EOF when reading a line, EOFError, args: {'query': "_query string removed_"}`

I looked at tool.py but couldn't figure out where it's going wrong.
![image](https://github.com/TransformerOptimus/SuperAGI/assets/26247323/63cc1ad6-991b-437d-b351-e1716c28f35d)

**Comment by neelayan7** [comment]
Human tool is not fully functional right now. It's still under development.

**Comment by merlinfrombelgium** [comment]
Fair enough :)

Let me know if I can contribute in any way!

**Comment by neelayan7** [comment]
@merlinfrombelgium sure. Let's connect more in the discord server: https://discord.com/invite/dXbRe5BHJC .
Meanwhile I'll close this issue as we have temporarily removed Human Tool and added Action console as a means for people to give feedback to their agent.
