### ISSUE TITLE
Integration with other open source models

### ISSUE THREAD

**Issue by Phoenix2809** [TransformerOptimus/SuperAGI#27]
I've been playing around with other language models such as GPT4all, Vicuna 13B, Alpaca and the results have been promising so far. Is there any way for me to test SuperAGI with other open source models? That would be great!

**Comment by amunrarara** [comment]
Bump on this! Just getting into the project, curious to see how this one evolves

**Comment by amunrarara** [comment]
@Phoenix2809 Maybe scoot to a discussion, instead of an issue?

**Comment by amunrarara** [comment]
There's been a PR! : https://github.com/TransformerOptimus/SuperAGI/pull/289

**Comment by neelayan7** [comment]
Local LLM support is currently live. Follow here: https://github.com/TransformerOptimus/SuperAGI/pull/289
Hence closing this.
