### ISSUE TITLE
Read file  and write file tools not working 

### ISSUE THREAD

**Issue by sursma** [TransformerOptimus/SuperAGI#271]
I keep getting error 
Unknown tool 'ReadFile'. Please refer to the 'TOOLS' list for available tools and only respond in the specified

**Comment by neelayan7** [comment]
Are you using 3.5? Please mention Agent Goals and Description as well.

**Comment by jolonbankey-AI** [comment]
I am getting the same error. 

On OSX. 
Using GPT 3.5

Goals:
1. business plan for aquaponics business selling freshwater seafood in los angeles
2. write the plan to a file

**Comment by stuinfla** [comment]
I'm having the same problem.  I set the folder but it does not read from the folder.   Or I add it right to the resource manager and it still cannot find it.      Is there a syntax we need to do?  what do we need to state to make it work?

**Comment by neelayan7** [comment]
Have you made the change required in the config.yaml?

#AUTH
ENV: 'DEV' #DEV,PROD, to use GITHUB OAUTH set to PROD
JWT_SECRET_KEY: 'secret'
expiry_time_hours: 1

Try adding this if this is not there.

**Comment by jasuca** [comment]
If you are on a mac you need to add permissions to fulldisk access under System preferences > Privacy & Security > Full Disk Access and add Docker

**Comment by neelayan7** [comment]
Closing this as we have resolved this issue.
