### ISSUE TITLE
How can I use Redis?

### ISSUE THREAD

**Issue by W01v3n** [TransformerOptimus/SuperAGI#281]
I really don't understand this and it's very annoying. Why is there redis configuration options in config.yaml?
You didn't document anything about how to setup this with anything other than Pinecone, which now I can't use because they put me in a waitlist.

I do appreciate what you've done so far, but I really don't understand how can I use it. I have a ready Redis instance, with no password authentication, all defaults and it works, now I need to know how to integrate SuperAGI with it.
I can see there are some parameters to connect to Redis, but I have no idea how to use them, for example, the password field- if there is no password, then an empty string ("") ? And what is PostgreSQL doing there? Isn't it either Pinecone or Redis?

Please explain further, it's really frustrating.

**Comment by luciferlinx101** [comment]
@W01v3n we are promoting people to run inside docker with one command ```docker compose up --build``` rather than locally setting up psql,redis etc.

Also just to clarify redis is being used inside celery set for running each iteration of agent.

**Comment by W01v3n** [comment]
> @W01v3n we are promoting people to run inside docker with one command `docker compose up --build` rather than locally setting up psql,redis etc.
> 
> Also just to clarify redis is being used inside celery set for running each iteration of agent.

Thank you for your reply @luciferlinx101 !

I have no problem doing it with docker, I'm quite for it.

So you're telling me there is no way to do it with long-term memory with anything other than Pinecone? Because there is not option to do that now, I registered and they put me in a waiting list.

So there is no point of using Redis? I didn't really understand what you said about it.

Thanks!

**Comment by hsm207** [comment]
the [redis.py](https://github.com/TransformerOptimus/SuperAGI/blob/main/superagi/vector_store/redis.py) file under the vector_store directory is empty (main branch). So, the only vector store option at the moment is Pinecone.

**Comment by W01v3n** [comment]
So there is no option to use this software until Pinecone decides I can, great.

**Comment by hsm207** [comment]
or...stay tuned for #93  😁
