### ISSUE TITLE
Interested in LanceDB integration

### ISSUE THREAD

**Issue by AyushExel** [TransformerOptimus/SuperAGI#288]
Hey guys, great work on this. I'm from LanceDB, a serverless vector database. I was exploring this project and I want to build an integration. Would you guys be interested? If so, I can make a PR. Thanks!

**Comment by luciferlinx101** [comment]
Yes @AyushExel that will be great do raise a PR.

**Comment by AyushExel** [comment]
Thanks guys. I'll try to do it by next week.

**Comment by AyushExel** [comment]
@luciferlinx101 @TransformerOptimus Hey guys, quick question - can you point me to an example that I can run to test the tool with long term memory enabled? I think I might be doing something wrong - I've added openai key and ran an agent.
I've not setup other things like search engine key as I just wanted to test. If there's an example agent that is used for testing, that'd be helpful. Thanks!

**Comment by luciferlinx101** [comment]
@AyushExel as of now Long term memory is under development you need to test it at your end.
