### ISSUE TITLE
Issues with Google Search

### ISSUE THREAD

**Issue by luiscosio** [TransformerOptimus/SuperAGI#291]
Hello!

I've configured my API keys and with each search I'm getting this error:

`superagi-celery-1           | [2023-06-09 18:54:28,453: WARNING/ForkPoolWorker-7] Tool Response : {'result': "Tool google search returned: Error1: list index out of range, IndexError, args: {'query': 'WHOIS lookup XX'}", 'retry': False}`

Any idea?

**Comment by luciferlinx101** [comment]
@luiscosio 
Can you share the exact goal and all agent details? To reproduce the issue at our end.

**Comment by neelayan7** [comment]
@luiscosio are you still facing the same issue?

**Comment by neelayan7** [comment]
@luiscosio ?
