### ISSUE TITLE
Agents communicating with each other

### ISSUE THREAD

**Issue by Phoenix2809** [TransformerOptimus/SuperAGI#30]
Hi guys

I was just wondering if we can make the agents conversational - as in each agent communicates with each other in order to get the assign tasks completed ?

**Comment by neelayan7** [comment]
We are introducing agent cluster with master slave architecture in v0.0.8. I think that is what you're looking at?

**Comment by neelayan7** [comment]
Tracking Agent Cluster related issues here: https://github.com/TransformerOptimus/SuperAGI/issues/572. Hence closing this.
