### ISSUE TITLE
test image generator error 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#300]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/tmp/image1.png'
  File "C:\Users\darre\SuperAGI\superagi\tools\image_generation\dalle_image_gen.py", line 58, in _execute
    with open(final_path, mode="wb") as img:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darre\SuperAGI\tests\tools\image_gen_test.py", line 30, in test_image_gen_tool_execute
    response = tool._execute(prompt, image_names, size, num)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/image1.png'

**Comment by luciferlinx101** [comment]
@DMTarmey Thanks for letting us know.
Can you as of now change the folder name or directory from /tmp/ to something which exisits in windows, in Image Generator Test rest we will fix it at our end in the coming release.

**Comment by DMTarmey** [comment]
cheers ill do that
