### ISSUE TITLE
Option to change tools for a new run

### ISSUE THREAD

**Issue by pallasite99** [TransformerOptimus/SuperAGI#305]
Here for a new run, there is no available option to add / remove a tool for re-running an agent.

![image](https://github.com/TransformerOptimus/SuperAGI/assets/26508636/c9906c20-14e6-46af-86ae-508eac265152)

Can that be introduced assuming it is possible?

**Comment by luciferlinx101** [comment]
@pallasite99 Currently you can only change the goals of the agents in a new run. For changing tools you need to create a new a new agent.
