### ISSUE TITLE
Incorrect output files contents

### ISSUE THREAD

**Issue by bitnom** [TransformerOptimus/SuperAGI#309]
Upon having it generate some code for me as produced .py files with contents such as:

```
server code
```

and:

```
updated client code with encryption
```

Though I haven't looked at the actual SuperAGI code, one would suspect some parsing issue and/or lack of error-handling.

edit: come to think of it, it sounds more like a prompting/response issue.

**Comment by hanhyalex123** [comment]
Can you screenshot the goal and tools you use

**Comment by neelayan7** [comment]
Coding Tool is now enhanced to solve these kind of problems. Closing this as this is solved.
