### ISSUE TITLE
⭐️⭐️⭐️Agents Continuously Run⭐️⭐️⭐️

### ISSUE THREAD

**Issue by AIProDeveloper** [TransformerOptimus/SuperAGI#312]
The problem I have now, is that agents are running in the background even if they have been stopped. I would like to just delete the agent completely. Is there a way to do that in the code or stop the agent from running and wasting tokes? 

I have to completely end the program to get the agents to stop; which doesn't allow me to setup new agents or tests.

Seem to be in a bind... 
<img width="683" alt="Screenshot 2023-06-11 at 2 16 52 AM" src="https://github.com/TransformerOptimus/SuperAGI/assets/130807420/9274668d-01ef-457f-b6b3-78499a65c13d">

**Comment by AIProDeveloper** [comment]
After 4 hours, finally figured out how to delete agents.

**Comment by AIProDeveloper** [comment]
![Screenshot 2023-06-11 at 9 01 56 PM](https://github.com/TransformerOptimus/SuperAGI/assets/130807420/58f2462a-3e81-4254-8e00-c33b60f54ed4)
![Screenshot 2023-06-11 at 9 02 00 PM](https://github.com/TransformerOptimus/SuperAGI/assets/130807420/9e28d48d-1efe-4015-8f56-f668a48b1f7e)

**Comment by luciferlinx101** [comment]
@AIProDeveloper if you stop the docker or docker compose down agents won't run, celery needs to be up for agents to run.

**Comment by AIProDeveloper** [comment]
Yes, closing docker is the only way, but if I start the app, it still does query requests. Only way to stop is to delete the agent entirely.
