### ISSUE TITLE
Differences between screenshot in readme and what tool looks like

### ISSUE THREAD

**Issue by RickyEsclapon** [TransformerOptimus/SuperAGI#319]
Hey, love what you guys are building, super cool. 

I was curious about the differences between the screenshot shown in the repo:
![image](https://github.com/TransformerOptimus/SuperAGI/assets/89109989/01cd95b6-bf5c-476d-b33e-742f2227fbb8)

And what I see when I run the tool:
<img width="1471" alt="image" src="https://github.com/TransformerOptimus/SuperAGI/assets/89109989/11aef208-d26c-4032-bae8-57babf1059c1">

I don't see the Action Console and Feedback tabs in the top right. I also don't see Agent Cluster, APM, and Embeddings in the left-most sidebar. The Action Console in particular would be really useful, would love to understand how to get that working.

**Comment by luciferlinx101** [comment]
@RickyEsclapon Action Console, Feedback,Embeddings and APM are currently under development you will soon see them in up coming releases.
