### ISSUE TITLE
Parsing PDFs

### ISSUE THREAD

**Issue by Phoenix2809** [TransformerOptimus/SuperAGI#32]
Has a tool been made to parse PDFs into SuperAGI? I'd like to give SuperAGI the ability to access a PDF file.

**Comment by neelayan7** [comment]
We are integrating Llama Index with Resource Manager which will help agents ingest PDFs, PPTs, docx, etc. Will be going live today!

**Comment by neelayan7** [comment]
Closing this issue as done.
