### ISSUE TITLE
Invalid next.config.js options detected:

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#322]
superagi-gui-1              | - warn Invalid next.config.js options detected:
superagi-gui-1              | - warn     The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, target, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
superagi-gui-1              | - warn See more info here: https://nextjs.org/docs/messages/invalid-next-config

**Comment by Fluder-Paradyne** [comment]
we'll remove webpackDevMiddleware from config
it was added to make sure nextjs hotreload work in windows 

for now you can comment it out 

`/** @type {import('next').NextConfig} */
const nextConfig = {
    assetPrefix: process.env.NODE_ENV === "production" ? "/" : "./"
}

module.exports = nextConfig
`

**Comment by Fluder-Paradyne** [comment]
#326 once it is merged it should be resolved
