### ISSUE TITLE
Finally figuring out how to delete agents....

### ISSUE THREAD

**Issue by AIProDeveloper** [TransformerOptimus/SuperAGI#325]
After a 4 hour day of looking through code and the database, finally, the day has come! 

![Screenshot 2023-06-11 at 9 01 56 PM](https://github.com/TransformerOptimus/SuperAGI/assets/130807420/cecd6814-a603-4dae-a736-703cc2692a7b)
![Screenshot 2023-06-11 at 9 02 00 PM](https://github.com/TransformerOptimus/SuperAGI/assets/130807420/954c7630-9bcb-40b1-ad58-39d3dad810cc)

**Comment by luciferlinx101** [comment]
@AIProDeveloper Hey this way is only for current version, in upcoming version you will have option in UI to delete agents.

**Comment by AIProDeveloper** [comment]
Thanks Buddy!
