### ISSUE TITLE
Stop sending unsoliticed spam emails!

### ISSUE THREAD

**Issue by tedmiston** [TransformerOptimus/SuperAGI#338]
As you are aware, spamming people by scraping their email address and other contact info from GitHub is a violation of the GitHub ToS that can result in getting your account banned.

https://docs.github.com/en/site-policy/github-terms/github-terms-of-service

I never gave you or your any company permission to contact me.

Screenshot of spam contact:

<img width="1792" alt="Screen Shot 2023-06-12 at 12 01 36 PM" src="https://github.com/TransformerOptimus/SuperAGI/assets/366688/e01fa78b-b377-48d5-b63a-0274a66fd9e2">

**Comment by Malfrador** [comment]
Great way to ruin a project that might otherwise have been interesting.

**Comment by tedmiston** [comment]
@Malfrador It is standard practice to report to GitHub directly and post an issue for community visibility when this happens.  Some people also post to HN.

Holding companies accountable for sending spam is not "spam" itself, so please stop with that nonsense.

The GitHub ToS are very clear that this is not permitted.
