### ISSUE TITLE
Feature Request - Code/API documentation tool

### ISSUE THREAD

**Issue by abhijeetaman007** [TransformerOptimus/SuperAGI#341]
Hey I am liking SuperAGI but I want few of my use cases to be full-filled like writing full documentation of the project along with API documentation with HTTP request,response (API contracts) by reading my code from github

But as of now I guess this whole case is not supported would love to see such use cases being to be solved.

This feature could actually make superagi more useful for my use-case.

**Comment by Autocop-Agent** [comment]
Hey, we are adding the GitHub tool in the next release which will allow you to interact with your GitHub repos. We already have a coding tool for writing codes and documentations.
