### ISSUE TITLE
I cannot see the output - despite multiple iterations and the agent stating that the document is prepared

### ISSUE THREAD

**Issue by Phoenix2809** [TransformerOptimus/SuperAGI#342]
So I let an agent and I had expected a document as an output. As you can see in the attached image below, the agent claimed to have completed making the document and proceeded with the next task. However when I check the resource manager, there's absolutely nothing as an output. Why is this happening? 

Also note, the agent took 20 iterations yet it could not complete the task.

![image](https://github.com/TransformerOptimus/SuperAGI/assets/133874957/4d3ef780-478c-4df2-be24-f0f65c6e9d5c)

**Comment by alanbrantley** [comment]
I have the same issue with the output tabs of the resource manager. 

You should be able to find your output files in the Workspace folder of your project file. 

Also finding that the agent has a hard time completing complex tasks.

**Comment by neelayan7** [comment]
This is now solved with newer version releases!
