### ISSUE TITLE
The tools option is not working!

### ISSUE THREAD

**Issue by Dev-Monster1** [TransformerOptimus/SuperAGI#344]
![image](https://github.com/TransformerOptimus/SuperAGI/assets/135033604/7cbe1192-33cb-42b0-8bc7-c2546fa86ad3)

When I try to click the tools which are available in the SuperAGI, it takes me nowhere. It will be helpful if the team could resolve this issue.

**Comment by neelayan7** [comment]
The tools list just shows you the tools that are available for you to use when you run and create an agent. To know more about the tools, kindly refer to the Readme files in the tools folder for respective tools.

**Comment by neelayan7** [comment]
Tools configuration along with their readme's are now being showed in the Front-End. Hence closing this issue.
