### ISSUE TITLE
⚠Not able to understand this project

### ISSUE THREAD

**Issue by Arvind1902** [TransformerOptimus/SuperAGI#345]
I am not a developer, but curious to know more about this project. Can I get some videos for tutorials?

**Comment by luciferlinx101** [comment]
Hey @Arvind1902 you can checkout 
https://youtu.be/iSPHZ1onQ44 
https://youtu.be/Unj5NLNTkLY
Else you can join the waitlist for our web app at https://superagi.com

**Comment by neelayan7** [comment]
Closing this issue.
