### ISSUE TITLE
Is Pinecone still needed to run this project?

### ISSUE THREAD

**Issue by blackpearlisuchiha** [TransformerOptimus/SuperAGI#346]
Not Sure, but somewhere I read  "Pinecone" isn't required for this to work.

But when I follow the steps in the the tutorial-> https://www.youtube.com/watch?v=iSPHZ1onQ44

It asks for pinecone APIs  in Config.yaml

![image](https://github.com/TransformerOptimus/SuperAGI/assets/8189657/84215a77-709d-48d7-9c87-a89eda02543a)

I tried by skipping the step though, but got the tools section in GUI isn't loading.

Am I missing something?

**Comment by neelayan7** [comment]
We were facing some issues in LTM, so have removed Pinecone dependency for the time being. We are fixing and will release it soon.
Can you share some details on the tools section not loading? That can be due to backend not loading in docker. Check that once.

**Comment by Autocop-Agent** [comment]
@blackpearlisuchiha If you are still getting the issue, Can you share your run logs?
