### ISSUE TITLE
Can't see the ports  on GitHub Codespaces

### ISSUE THREAD

**Issue by Webmaster341** [TransformerOptimus/SuperAGI#348]
I guess I am doing something wrong.

![image](https://github.com/TransformerOptimus/SuperAGI/assets/135034381/3fe1e234-afcb-472c-975a-7e4f52412328)

The build looks like to be completed, but can't see the ports though

any idea why?
![image](https://github.com/TransformerOptimus/SuperAGI/assets/135034381/66e7c053-d01a-4f34-b9df-0aa1dcf901ef)

**Comment by luciferlinx101** [comment]
@Webmaster341 This is some issue of GitHub codespaces can you try deleing the current codespace and create new one and try to build again?

**Comment by neelayan7** [comment]
Is this issue solved?

**Comment by mdabir1203** [comment]
<img width="855" alt="image" src="https://github.com/TransformerOptimus/SuperAGI/assets/66947064/4b635b58-5721-4aed-a4f7-42061abb9f9c">

I am seeing this issues while in codespaces
