### ISSUE TITLE
lxml error while setting up 

### ISSUE THREAD

**Issue by rocket-raccoon-v3** [TransformerOptimus/SuperAGI#349]
Hi, 
I am facing issues while setting up the repository locally.

Steps to reproduce:
1. Download repo
2. Install the needful as mentioned in repo docs

Getting the following error
`Collecting lxml
  Using cached lxml-4.9.2.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
      Building lxml version 4.9.2.`

Tried the following but nothing worked
`source /Users/anirudh/contlo/SuperAGI/venv/bin/activate\npip install lxml==4.9.2`
`pip3 install lxml`

Any suggestions

**Comment by Autocop-Agent** [comment]
Can you try to run it after updating your pip version? Also send your logs if it doesn't work
