### ISSUE TITLE
REQ: Easily set the exposed URL via GUI

### ISSUE THREAD

**Issue by atxcowboy** [TransformerOptimus/SuperAGI#363]
Hi, 

I am not usually a Windows user, but my AI stuff runs on a Windows computer, so **please** forgive my ignorance.
I only got SuperAGI running by adding 127.0.0.1 to the main.py CORS config, replacing localhost with 127.0.0.1 and the port 3000 with a higher port like 7900 in the docker-compose.yaml and the config.yaml. 
While being able to modify .yaml files can be expected from an Open Source user, having to modify a core file like main.py is not elegant.

I assume all of this could have been overcome by fiddling more with the Windows configs, but at the various places I looked for solutions I noticed that other people ran into the same issues and some gave up, decided to review later again, etc. 

Thus, to be more inclusive, I'd like to ask to have a GUI functionality where you can set the app to another exposed URL or domain (similar to setting a new OpenAI key), have it automatically honor this URL for CORS and not have to go back to overwrite core files like main.py.

In that config you could also decide if you want to run the bundled dockerized Oobabooga or point it to your own customized version, maybe sync the available models, etc.

Thanks for your attention.
Ciao
        Sascha

**Comment by atxcowboy** [comment]
I guess using nginx in front of the services as I can see with a pending PR may take care of the issue.

**Comment by neelayan7** [comment]
Nginx is now implemented.
