### ISSUE TITLE
Connecting SuperAGI with Weviate and Mivus

### ISSUE THREAD

**Issue by Akki-jain** [TransformerOptimus/SuperAGI#37]
What if we can have Weviate and Mivus as vector databases along with Pinecone?

**Comment by deece** [comment]
I'd suggest redis vector support too, it works well enough for AutoGPT. Pgvector could also be interesting, given the reliance on Postgres anyway

**Comment by neelayan7** [comment]
We have added Chroma, Weviate, Redis, Pinecone. Will add Mivus in the future. 
Deleting this issue for now.
