### ISSUE TITLE
Could not parse invalid json

### ISSUE THREAD

**Issue by linhcentrio** [TransformerOptimus/SuperAGI#391]
i only run WebScraperTool but usually have this error:
![image](https://github.com/TransformerOptimus/SuperAGI/assets/45778128/d0052bf2-c9c4-4ea0-a481-85e6601bf6dc)

**Comment by neelayan7** [comment]
This is a bug that we are facing with Web Scraper. We are working on this.

**Comment by neelayan7** [comment]
Some one in the community mentioned this. Try this out: 

"I think not escaping the double quotes is the issue..You could try inserting into the agent's description, or as a goal, something like: 

REMEMBER to format your response as JSON, using double quotes ("") around keys and string values, and commas (,) to separate items in arrays and objects. IMPORTANTLY, to use a JSON object as a string in another JSON object, you need to escape the double quotes.

I've found it helps"

**Comment by neelayan7** [comment]
We've added this along with the Constraints while creating an agent. No longer getting this issue. 
Thus closing this. 
If you feel this is not completely solved, feel free to open it again and we can help you out.
