### ISSUE TITLE
Unknown tool "xxx"

### ISSUE THREAD

**Issue by Nanky586** [TransformerOptimus/SuperAGI#410]
I have no idea what im doing and im not one of you guys. But i know how to google and i didnt find an answer so i ask here.

When SuperAGI runs on standard settings (gpt-3.5-turbo, GoogleSearch + Read File + Write File, no advanced Options) it keeps suggesting itself to run tools it doesnt have and then fails to run them.

![Screenshot 2023-06-17 at 17 34 34](https://github.com/TransformerOptimus/SuperAGI/assets/136914912/de5c60f0-9421-4b78-902c-a0d51b7ecfae)

Is that normal? Am i doing something wrong?

**Comment by iskandarreza** [comment]
Its not your fault, you did nothing wrong, `gpt-3.5-turbo` has been known to hallucinate like that sometimes. I found that setting the advanced option "maintain task queue" helps sometimes.

**Comment by neelayan7** [comment]
@iskandarreza correct. Try using GPT-4 with similar goals and description, that'll help

**Comment by Nanky586** [comment]
Thank you so much for your help. I will try that.
