### ISSUE TITLE
=> ERROR [backend  5/10] RUN pip install --no-cache-dir -r requirements.txt

### ISSUE THREAD

**Issue by PierrunoYT** [TransformerOptimus/SuperAGI#445]
=> ERROR [backend  5/10] RUN pip install --no-cache-dir -r requirements.txt

**Comment by neelayan7** [comment]
Can you share some more detailed logs?

**Comment by PierrunoYT** [comment]
> Can you share some more detailed logs?

I tried to build with Docker

**Comment by Autocop-Agent** [comment]
Can you share the docker log?

**Comment by PierrunoYT** [comment]
> Can you share the docker log?

Where is it?

**Comment by neelayan7** [comment]
In your terminal from where you did docker compose up.

**Comment by PierrunoYT** [comment]
> In your terminal from where you did docker compose up.

I tried again today and it's still building
