### ISSUE TITLE
feature request - or not...

### ISSUE THREAD

**Issue by danntata** [TransformerOptimus/SuperAGI#449]
Is there a way to have these agents access a website running on chrome. For example a good use case, I have an ecommerce web app, which I am trying to populate with product description, I want to create an agent and give it directives to visit my web app dashboard, click on "items", click the first item on the list "apples", and then write the product description for apples in the description section.

**Comment by Tdmain** [comment]
Don’t want google on the platform, with this and if you can, who am I speaking with?

Thank you,
owner GitHub.com

Ross Nicholas Oneil Thomas
Sent from my iPhone

On Jun 22, 2023, at 12:11 PM, danntata ***@***.***> wrote:

﻿

Is there a way to have these agents access a website running on chrome. For example a good use case, I have an ecommerce web app, which I am trying to populate with product description, I want to create an agent and give it directives to visit my web app dashboard, click on "items", click the first item on the list "apples", and then write the product description for apples in the description section.

**Comment by danntata** [comment]
My name is Dan, just wondering if we can have a feature to access web browsers not necessarily chrome, for a use case as I have described above. Multi-On seem to be doing this. In essence let's have the agents that can run browser or web based based tasks, maybe using selenium or puppeteer. 

Thanks.

**Comment by Tdmain** [comment]
I don’t want google Crome on the webpage GitHub.com at all. Can you do something to take them off

Sent from my iPhone

On Jun 22, 2023, at 2:01 PM, danntata ***@***.***> wrote:

﻿

My name is Dan, just wondering if we can have a feature to access web browsers not necessarily chrome, for a use case as I have described above. Multi-On seem to be doing this. In essence let's have the agents that can run browser or web based based tasks, maybe using selenium or puppeteer.

Thanks.

**Comment by Tdmain** [comment]
We have our own clouds and I really want them off this platform, they get to much into our stuff and there’s a editor that’s doing google git I can’t have them on here branching or doing beanchbrepos and taking our stuff else ware, I’m in a base battle to say right now. Illegal one for sure not played fare or to my knowledge until recent and I’m working on them now best I can

Sent from my iPhone

On Jun 22, 2023, at 4:50 PM, ross thomas ***@***.***> wrote:

﻿ I don’t want google Crome on the webpage GitHub.com at all. Can you do something to take them off

Sent from my iPhone

On Jun 22, 2023, at 2:01 PM, danntata ***@***.***> wrote:

﻿

My name is Dan, just wondering if we can have a feature to access web browsers not necessarily chrome, for a use case as I have described above. Multi-On seem to be doing this. In essence let's have the agents that can run browser or web based based tasks, maybe using selenium or puppeteer.

Thanks.

**Comment by neelayan7** [comment]
@danntata we are launching a Web Interactor tool that will help you achieve exactly what you mentioned.

**Comment by danntata** [comment]
> @danntata we are launching a Web Interactor tool that will help you achieve exactly what you mentioned.

Thanks for the response, looking forward to it.
