### ISSUE TITLE
Proxy and Upstream Errors

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#456]
Proxy and Upstream Errors: There are several errors indicating issues with connecting to upstream servers. The error messages mention connection timeouts and connection refusal. This could indicate a problem with the network configuration or the availability of the upstream servers.

**Comment by luciferlinx101** [comment]
@DMTarmey Can you share the errors.

**Comment by DMTarmey** [comment]
sorry i scrapped it as couldn't get it to run and when on to more stable branch
