### ISSUE TITLE
There are multiple GET requests for various resources like JavaScript files

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#457]
GET Requests: There are multiple GET requests for various resources like JavaScript files (_next/static/chunks/*.js), an SVG image (/images/sign-in-logo.svg), and others. These requests seem to be related to the application or website being accessed.

**Comment by luciferlinx101** [comment]
Can you give more details on the issue.

**Comment by DMTarmey** [comment]
sorry iv moved on cant remember what i did
