### ISSUE TITLE
Building with Docker takes too much time

### ISSUE THREAD

**Issue by PierrunoYT** [TransformerOptimus/SuperAGI#464]
It takes so much time to build with Docker

**Comment by luciferlinx101** [comment]
Hey yeah first time it takes time, you can wait a little

**Comment by anmandsu** [comment]
> 使用 Docker 构建需要花费很多时间
需要多久呢我构建了十几个小时了

**Comment by anmandsu** [comment]
> It takes so much time to build with Docker

How long will it take? I've been building for more than ten hours

**Comment by PierrunoYT** [comment]
> > It takes so much time to build with Docker
> 
> 
> 
> How long will it take? I've been building for more than ten hours

I found the problem. I had not enough space on my drive. Maybe it could also be because of slow internet connection.
