### ISSUE TITLE
not reading PDF uploaded to input

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#468]
I uploaded my own cv and then asked the software to find out about me, it ignored the cv pdf file, attempted to search google and missed all the data on Darren Tarmey and them made stuff up.

**Comment by luciferlinx101** [comment]
@DMTarmey Hey currently we don't support reading pdf soon it will be supported.

**Comment by DMTarmey** [comment]
OK cheers

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
