### ISSUE TITLE
Error on login with github, ENV variables is not set in GUI container

### ISSUE THREAD

**Issue by crazynds** [TransformerOptimus/SuperAGI#476]
Hello,
I was trying to up a clean instalation in PROD mode in my server but I'm getting a error when I try to login with github.

When I click in the github icon the page redirect me to:
```
https://github.com/login/oauth/authorize?scope=user:email&client_id=undefined
```
This link redirect me to 404 of github website.

I was reading the code and I notice the ```process.env``` in gui container is empty.
The follow line return undefined and this is placed in the url.
```js
export const githubClientId = () => {
  return GITHUB_CLIENT_ID;
};
```
I can't find where the env variables were set and no .env should be created.

**Comment by Tdmain** [comment]
Scooping the id is why I made things so we couldn’t copy people stuff and steal there money

Sent from my iPhone

On Jun 24, 2023, at 11:23 AM, Crazynds ***@***.***> wrote:

﻿

Hello,
I was trying to up a clean instalation in PROD mode in my server but I'm getting a error when I try to login with github.

When I click in the github icon the page redirect me to:

https://github.com/login/oauth/authorize?scope=user:email&client_id=undefined


This link redirect me to 404 of github website.

I was reading the code and I notice the process.env in gui container is empty.
The follow line return undefined and this is placed in the url.

export const githubClientId = () => {
  return GITHUB_CLIENT_ID;
};

I can't find where the env variables were set and no .env should be created.

**Comment by crazynds** [comment]
@Tdmain what you said makes no sense, has no context, and does nothing to help this issue.

I don't know where the correlation is between the env variables not defined in the frontend and scooping the id of somewhere.

**Comment by eqxwow** [comment]
@crazynds @Techfluent-au Thanks for reporting.

Please join our discord community https://discord.gg/VzFXWu2q
Let's discuss what you are trying to setup in discord.

**Comment by Tdmain** [comment]
What makes you think your Tdmain I started this webpage and that’s what’s going on, people are using other peoples stuff and I’m trying to obtain my accounts that were never given away! Send me and I’ll send with you to the offices to sort things out. Otherwise you’ll lose your work then I’ll try and make sure you get your back and I have mine! 559-816-2950
