### ISSUE TITLE
Memory Overcommit Configuration Issue in Docker Environment

### ISSUE THREAD

**Issue by Lebo124** [TransformerOptimus/SuperAGI#477]
I've been experiencing an issue with SuperAGI's Docker setup where the application gets stuck in a "thinking" loop and doesn't return any output.

From an open issue (#390), I found that this could be due to the 'vm.overcommit_memory' setting not being enabled. I attempted to enable this setting by entering into the Docker container for the SuperAGI backend and running the command sysctl vm.overcommit_memory=1 as root, but I received a "permission denied" error.

It seems that I'm unable to modify this setting within the Docker container. I'm unsure if this is due to how the Docker container is configured, or if this setting needs to be adjusted at the host machine level.

Could you provide some guidance on how to resolve this issue? Is there a specific Docker container configuration that allows the modification of this setting, or should this be adjusted on the host machine instead?

Thank you in advance for your assistance.

**Comment by eqxwow** [comment]
@Lebo124 This is a very uncommon issue. You can try a clean install once.

Please join our discord community https://discord.gg/VzFXWu2q
We can discuss on Discord.
