### ISSUE TITLE
need a documentation how to implement more tools

### ISSUE THREAD

**Issue by mafel786** [TransformerOptimus/SuperAGI#481]
MS Excel, GoogleSholar, GoogleSheets, openpyxl, Pubmed_search, Scopus

**Comment by mramitdas** [comment]
please do let me know too

**Comment by mramitdas** [comment]
> We're adding a way where we can add external tools easily. Hopefully in the next 1-2 days!

Looking forward ☺️

**Comment by neelayan7** [comment]
This is now live. Checkout this blog: https://superagi.com/adding-your-own-custom-tool-toolkit-to-superagi/
