### ISSUE TITLE
Unable to kill SuperAGI docker container

### ISSUE THREAD

**Issue by mramitdas** [TransformerOptimus/SuperAGI#500]
![image](https://github.com/TransformerOptimus/SuperAGI/assets/51442266/39848657-e18b-4d2c-95dc-1ed387fc26a6)

please refer to below back trace

Gracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 2/2
[+] Stopping 2/2eragi-celery-1  Error while Stopping                                                                                                     14.2s 
[+] Stopping 2/2eragi-celery-1  Error while Stopping                                                                                                     14.2s 
 ✘ Container superagi-celery-1  Error while Stopping

**Comment by mramitdas** [comment]
![image](https://github.com/TransformerOptimus/SuperAGI/assets/51442266/6f7ba689-a045-4bb7-a24a-3ec06c169d31)


> Can you try docker compose down?

**Comment by mramitdas** [comment]
> Try following commands `docker ps` - To list the containers running `docker stop <container_id>` - To gracefully stop a particular container id `docker kill <container_id>` - To force stop

![image](https://github.com/TransformerOptimus/SuperAGI/assets/51442266/e2dff55a-a2f5-4277-b205-9a87aeae9be6)

**Comment by luciferlinx101** [comment]
Can you try using commands as with ```sudo``` like sudo docker stop .. etc.

**Comment by mramitdas** [comment]
> Can you try using commands as with `sudo` like sudo docker stop .. etc.

![image](https://github.com/TransformerOptimus/SuperAGI/assets/51442266/a0df71f4-54ff-4adf-91ce-fef5bbd7187a)

**Comment by Autocop-Agent** [comment]
If you have a snap installed version of docker, you can do, `sudo aa-remove-unknown`, it will remove unknown snap packages and you can do `sudo docker compose down` after that

**Comment by neelayan7** [comment]
Is this solved? @mramitdas ?

**Comment by coder5492** [comment]
Closing this issue for now. Please reopen if required
