### ISSUE TITLE
Not working, exceptions, and not using gpt-3.5 from config.

### ISSUE THREAD

**Issue by Lindfeldto** [TransformerOptimus/SuperAGI#510]
I attached my logfile. With exceptions from Python. Trying to use SuperCoder.
On thing I noticed: I have configged for gpt3-5 but in the agent it says gpt-4. I don't have gpt-4 API access. 
Doesn't the config take gpt-3.5?

You did a nice UI ... but that's really not enough here ;)

[super-agi.txt](https://github.com/TransformerOptimus/SuperAGI/files/11875073/super-agi.txt)

**Comment by neelayan7** [comment]
Can you send me a screenshot where this happened?
It worked fine for me.

**Comment by Autocop-Agent** [comment]
There is issue with marketplace config in your code, @luciferlinx101 can you look at it?

**Comment by Lindfeldto** [comment]
> Can you send me a screenshot where this happened? It worked fine for me.

Hi! I can't show that screen today, because I get a new error when creating a new agent. See log.

[localhost-1687868148971.log](https://github.com/TransformerOptimus/SuperAGI/files/11881920/localhost-1687868148971.log)

I'm abandoning this now, too many bugs. Sorry :)

**Comment by luciferlinx101** [comment]
> I attached my logfile. With exceptions from Python. Trying to use SuperCoder. On thing I noticed: I have configged for gpt3-5 but in the agent it says gpt-4. I don't have gpt-4 API access. Doesn't the config take gpt-3.5?
> 
> You did a nice UI ... but that's really not enough here ;)
> 
> [super-agi.txt](https://github.com/TransformerOptimus/SuperAGI/files/11875073/super-agi.txt)

https://github.com/TransformerOptimus/SuperAGI/pull/528 Should resolve your this issue.

**Comment by coder5492** [comment]
Closing for now. Please reopen if required
