### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of null (reading 'scrollTo')

### ISSUE THREAD

**Issue by linhcentrio** [TransformerOptimus/SuperAGI#512]
![image](https://github.com/TransformerOptimus/SuperAGI/assets/45778128/df88c6d5-e2bc-4ada-9730-953e72a335e2)

**Comment by neelayan7** [comment]
@namansleeps is looking into this. Thanks for notifying!

**Comment by neelayan7** [comment]
https://github.com/TransformerOptimus/SuperAGI/pull/514
We've raised a PR to resolve this issue. Will be merged soon!

**Comment by neelayan7** [comment]
Merged to main. Can you please check again @linhcentrio ?

**Comment by linhcentrio** [comment]
> 

ok i will check it now.

**Comment by neelayan7** [comment]
@linhcentrio is this solved?

**Comment by linhcentrio** [comment]
> @linhcentrio is this solved?

yes, i reply that all ok!

**Comment by neelayan7** [comment]
Awesome. Closing this issue.
