### ISSUE TITLE
Bugfix [Safari]: "Save as Template" and "Pause" options not available

### ISSUE THREAD

**Issue by lukemmtt** [TransformerOptimus/SuperAGI#530]
The ability to stop or kill running agents is a crucial feature that is currently missing. This functionality would provide users with greater control over resource usage and the ability to halt agents that are not performing as expected or that have entered undesired states. 

(Issue title is intentionally wordy for searchability)

**Comment by lukemmtt** [comment]
@neelayan7 Can you elaborate on this? In the latest release (as well as in the main branch), I've been unable to suspend any agent in any way other than completely killing the superAGI instance.

**Comment by neelayan7** [comment]
When an agent is running, you'll see 3 dots on the Top-Right. Click on that, you'll see options to "Save as Template" and "Pause".

**Comment by lukemmtt** [comment]
> When an agent is running, you'll see 3 dots on the Top-Right. Click on that, you'll see options to "Save as Template" and "Pause".

In my builds (both the latest release and the main branch; deployed via docker, in both a GitHub Codespace and a local docker deployment), this "3 dot" menu did not populate the way you described.

I will try again today and report back.

**Comment by neelayan7** [comment]
Looking into this. Thanks for raising!

**Comment by neelayan7** [comment]
https://github.com/TransformerOptimus/SuperAGI/pull/544 Have raised a PR addressing this issue.

**Comment by lukemmtt** [comment]
Thanks so much!!

**Comment by lukemmtt** [comment]
https://github.com/TransformerOptimus/SuperAGI/pull/544 was merged to dev 🚀
