### ISSUE TITLE
Enhancement: Ability to edit / modify existing agents

### ISSUE THREAD

**Issue by lukemmtt** [TransformerOptimus/SuperAGI#531]
Currently, once an agent is created and started, there doesn't seem to be a way to modify its configuration or behavior without creating a duplicate agent using the "Save as Template" option. As such, if the user is experimenting with different parameters (Goals, GPT-3.5 vs 4) this missing feature (paired with the absence of [Enhancement: Ability to delete agents #529](https://github.com/TransformerOptimus/SuperAGI/issues/529)), makes for a cluttered dev environment.

To address that, I'd like to propose the addition of an **Edit** button that would allow modification of the elements in the Details pane. Even if the button were only made available while an agent is paused/stopped, that would serve the purpose in my view.

**Comment by DMTarmey** [comment]
Yes good call i agree

**Comment by neelayan7** [comment]
Right. We have a pause run and then delete run button. 
But not explicitly a delete agent button.
![image](https://github.com/TransformerOptimus/SuperAGI/assets/43145646/3aca8d65-5d82-4ebd-b478-5390a88a9fd3)

This is the proposed design for it. Deleting an agent would delete all the agent runs and all the data associated with it.

**Comment by agnes-sharan** [comment]
Hi is this issue still open for contribution?

**Comment by qwederpulz** [comment]
ocker compose up --buil
