### ISSUE TITLE
Failed to fetch on send magic link.

### ISSUE THREAD

**Issue by eXperitur** [TransformerOptimus/SuperAGI#539]
I've set up and got quivr running via docker compose, and the frontend loads fine - however, I get "failed to fetch" when i click "send magic link" (maybe docker having no internet access?). ...How can I fix this?

**Comment by neelayan7** [comment]
"Send Magic Link"? Are you sure it's relevant to this project?

**Comment by eXperitur** [comment]
awfully sorry, looks like I posted on the wrong screen! ;D
