### ISSUE TITLE
Provide context to the agent along with goals

### ISSUE THREAD

**Issue by eqxwow** [TransformerOptimus/SuperAGI#54]

**Comment by pratham-saraf** [comment]
@TransformerOptimus  hey i was looking to contribute to this project can you provide me further details regarding this?

**Comment by TransformerOptimus** [comment]
@pratham-saraf  You can join our discord community https://discord.gg/mVssSJNm . We will guide you on how to contribute.

**Comment by neelayan7** [comment]
We have added "Agent Instructions" along with goals to create an agent. Closing this.
