### ISSUE TITLE
Tests not running 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#547]
I have just installed main branch of code and ran the test but few failed:-

create event calendar "   def test_create_event_calendar_input_invalid(self):"
delete event test     @patch("your_module.GoogleCalendarCreds")
test invalide input AssertionError: ValidationError not raised
self = <delete_event_test.TestDeleteCalendarEventInput testMethod=test_invalid_input>

    def test_invalid_input(self):
        input_data = {"event_id": ""}
>       with self.assertRaises(ValidationError):
E       AssertionError: ValidationError not raised

tests\tools\google_calendar\delete_event_test.py:14: AssertionError

Test download tool

**Comment by neelayan7** [comment]
Can you share some more details on the errors?

**Comment by neelayan7** [comment]
https://github.com/TransformerOptimus/SuperAGI/actions/runs/5363508058/jobs/9833308119
Check this link, this was the google calendar PR that was merged. All tests ran and was successful.

**Comment by DMTarmey** [comment]
I pull latest updates
