### ISSUE TITLE
The output PDF document is damaged and cannot be opened！

### ISSUE THREAD

**Issue by limumua** [TransformerOptimus/SuperAGI#548]
When I tried to output a PDF document, I got it, but it couldn't be opened when downloaded locally，Does anyone know about this problem？？
![image](https://github.com/TransformerOptimus/SuperAGI/assets/40764041/2b362086-65bd-4eb5-813e-afa0c42a55f5)

**Comment by limumua** [comment]
When the output is a txt file, it can be opened normally

**Comment by neelayan7** [comment]
Currently we can't output pdf files as the Write Tool doesn't have that functionality yet. But thanks for raising, we'll discuss with the core team.

**Comment by limumua** [comment]
> Currently we can't output pdf files as the Write Tool doesn't have that functionality yet. But thanks for raising, we'll discuss with the core team.

Thank you for your reply. I understand！

**Comment by neelayan7** [comment]
Would be awesome if someone could pick up the task of outputting PDFs, docx, CSVs, etc from Write File Tool in SuperAGI.

**Comment by Arkajit-Datta** [comment]
Picking up this issue.
