### ISSUE TITLE
issue with dependencies clashing 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#553]
I have just tried so many combination of dependencies but can seem to find one thAT WORKS CAN YOU HELP PLEASE ? 

It seems that even after installing SQLAlchemy version 1.3.16, you're still encountering dependency conflicts. The packages langchain and superagi have specific requirements for SQLAlchemy versions that are incompatible with each other.

**Comment by Fluder-Paradyne** [comment]
yes, we are removing the conflicting dependency
it is due to `pydantic-sqlalchemy` which we use to convert sqlalchemy to pydantic models which are then used by fastapi for validation 

We are working on writing our own pydantic models

**Comment by Fluder-Paradyne** [comment]
```
from typing import Container, Optional, Type

from pydantic import BaseConfig, BaseModel, create_model
from sqlalchemy.inspection import inspect
from sqlalchemy.orm.properties import ColumnProperty


class OrmConfig(BaseConfig):
    orm_mode = True


def sqlalchemy_to_pydantic(
        db_model: Type, *, config: Type = OrmConfig, exclude: Container[str] = []
) -> Type[BaseModel]:
    mapper = inspect(db_model)
    fields = {}
    for attr in mapper.attrs:
        if isinstance(attr, ColumnProperty):
            if attr.columns:
                name = attr.key
                if name in exclude:
                    continue
                column = attr.columns[0]
                python_type: Optional[type] = None
                if hasattr(column.type, "impl"):
                    if hasattr(column.type.impl, "python_type"):
                        python_type = column.type.impl.python_type
                elif hasattr(column.type, "python_type"):
                    python_type = column.type.python_type
                assert python_type, f"Could not infer python_type for {column}"
                default = None
                if column.default is None and not column.nullable:
                    default = ...
                fields[name] = (python_type, default)
    pydantic_model = create_model(db_model.__name__, __config__=config, **fields)
    return pydantic_model
```

adding this file to code base and replacing imports to point to this file
and removing `pydantic-sqlalchemy `from requirements might help

**Comment by DMTarmey** [comment]
Hi i just pull lattest fixes and still getting the error "    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behabotocore 1.29.146 requires urllib3<1.27,>=1.25.4, but you 
google-auth 2.19.1 requires urllib3<2.0, but you have urllib3 2.0.3 which is incompatible.
llama-index 0.6.35 requires urllib3<2, but you have urllib3 2.0.3 which is incompatible.
pyppeteer 1.0.2 requires urllib3<2.0.0,>=1.25.8, but you have urllib3 2.0.3 which is incompatible.
qdrant-client 1.3.1 requires urllib3<2.0.0,>=1.26.14, but 
you have urllib3 2.0.3 which is incompatible.
superagi 0.0.26 requires fastapi==0.96.0, but you have fastapi 0.98.0 which is incompatible.
superagi 0.0.26 requires SQLAlchemy==2.0.15, but you have 
sqlalchemy 2.0.17 which is incompatible.
Successfully installed urllib3-2.0.3
PS C:\Users\Dell User\SuperAGI> pip uninstall numpy       
Found existing installation: numpy 1.25.0
Uninstalling numpy-1.25.0:
  Would remove:
    c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages\numpy-1.25.0.dist-info\*
    c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages\numpy\*
    c:\users\dell user\appdata\local\programs\python\python310\scripts\f2py.exe
Your response ('ninstall fastapi') was not one of the expected responses: y, n,
Proceed (Y/n)? pip uninstall urllib3
Your response ('pip uninstall urllib3') was not one of the expected responses: y, n,
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.25.0
PS C:\Users\Dell User\SuperAGI> pip uninstall sqlalchemy  
Found existing installation: SQLAlchemy 2.0.17
Uninstalling SQLAlchemy-2.0.17:
  Would remove:
    c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages\sqlalchemy-2.0.17.dist-info\*      
    c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages\sqlalchemy\*
Proceed (Y/n)? y
  Successfully uninstalled SQLAlchemy-2.0.17
PS C:\Users\Dell User\SuperAGI> pip u
PS C:\Users\Dell User\SuperAGI> pip install numpy==1.23.3 
Collecting numpy==1.23.3
  Using cached numpy-1.23.3-cp310-cp310-win_amd64.whl (14.6 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.langchain 0.0.218 requires SQLAlchemy<3,>=1.4, which is not installed.
llama-index 0.6.35 requires sqlalchemy>=2.0.15, which is not installed.
superagi 0.0.26 requires SQLAlchemy==2.0.15, which is not 
installed.
argilla 1.11.0 requires httpx<0.24,>=0.15, but you have httpx 0.24.1 which is incompatible.
llama-index 0.6.35 requires urllib3<2, but you have urllib3 2.0.3 which is incompatible.
qdrant-client 1.3.1 requires urllib3<2.0.0,>=1.26.14, but 
you have urllib3 2.0.3 which is incompatible.
superagi 0.0.26 requires fastapi==0.96.0, but you have fastapi 0.98.0 which is incompatible.
Successfully installed numpy-1.23.3
PS C:\Users\Dell User\SuperAGI> pip install sqlalchemy==1.3.16
Collecting sqlalchemy==1.3.16
  Using cached SQLAlchemy-1.3.16-cp310-cp310-win_amd64.whlInstalling collected packages: sqlalchemy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.langchain 0.0.218 requires SQLAlchemy<3,>=1.4, but you have sqlalchemy 1.3.16 which is incompatible.
llama-index 0.6.35 requires sqlalchemy>=2.0.15, but you have sqlalchemy 1.3.16 which is incompatible.
llama-index 0.6.35 requires urllib3<2, but you have urllib3 2.0.3 which is incompatible.
superagi 0.0.26 requires fastapi==0.96.0, but you have fastapi 0.98.0 which is incompatible.
superagi 0.0.26 requires SQLAlchemy==2.0.15, but you have 
sqlalchemy 1.3.16 which is incompatible.
0
Collecting fastapi==0.96.0
  Using cached fastapi-0.96.0-py3-none-any.whl (57 kB)    
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages (from fastapi==0.96.0) (1.10.8)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages (from fastapi==0.96.0) (0.27.0)      
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi==0.96.0) (4.5.0)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages (from starlette<0.28.0,>=0.27.0->fastapi==0.96.0) (3.7.0)
Requirement already satisfied: idna>=2.8 in c:\users\dell 
Requirement already satisfied: sniffio>=1.1 in c:\users\deackages (from anyio<5,>=3.4.0->starlette<0.28.0,>=0.27.0->fastapi==0.96.0) (1.3.0)
Requirement already satisfied: exceptiongroup in c:\users\dell user\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.28.0,>=0.27.0->fastapi==0.96.0) (1.1.1)
Installing collected packages: fastapi
  Attempting uninstall: fastapi
    Found existing installation: fastapi 0.98.0
    Uninstalling fastapi-0.98.0:
      Successfully uninstalled fastapi-0.98.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.superagi 0.0.26 requires SQLAlchemy==2.0.15, but you have 
sqlalchemy 1.3.16 which is incompatible.
Successfully installed fastapi-0.96.0
PS C:\Users\Dell User\SuperAGI> pip install urllib3==1.26.7
Collecting urllib3==1.26.7
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.3
    Uninstalling urllib3-2.0.3:
      Successfully uninstalled urllib3-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.llama-index 0.6.35 requires sqlalchemy>=2.0.15, but you have sqlalchemy 1.3.16 which is incompatible.
qdrant-client 1.3.1 requires urllib3<2.0.0,>=1.26.14, but 
you have urllib3 1.26.7 which is incompatible.
superagi 0.0.26 requires SQLAlchemy==2.0.15, but you have 
sqlalchemy 1.3.16 which is incompatible.
superagi 0.0.26 requires urllib3>=2.0.2, but you have urllib3 1.26.7 which is incompatible.
Successfully installed urllib3-1.26.7
PS C:\Users\Dell User\SuperAGI>
PS C:\Users\Dell User\SuperAGI> git fetch
PS C:\Users\Dell User\SuperAGI> git merge origin/main     
Already up to date.
PS C:\Users\Dell User\SuperAGI> git pull origin main      
From https://github.com/TransformerOptimus/SuperAGI
 * branch              main       -> FETCH_HEAD
Already up to date.
PS C:\Users\Dell User\SuperAGI> "

**Comment by DMTarmey** [comment]
should i pull from main branch have the dependency issue been solved there or is it on dev branch if so which branch ?

**Comment by Fluder-Paradyne** [comment]
ingest_multi_files is the branch 
but this branch is very volatile 
I am changing a lot of stuff and not tested

**Comment by DMTarmey** [comment]
so i'm having issue with merging, keep getting conflicts everywhere what is the most stable branch of this project at moment

**Comment by DMTarmey** [comment]
Cheers for fix
