### ISSUE TITLE
Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#568]
superagi-backend-1          | ERROR:    Application startup failed. Exiting.
superagi-celery-1           | [2023-06-30 10:54:39,863: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address..

**Comment by neelayan7** [comment]
Can you share some more detailed logs? Also, is the issue persisting?

**Comment by DMTarmey** [comment]
Sorry iv moved on and tried again with latest version !

**Comment by DMTarmey** [comment]
Sorry iv moved on and tried again with latterst version
