### ISSUE TITLE
Adding External Toolkits to Toolkit Marketplace

### ISSUE THREAD

**Issue by TransformerOptimus** [TransformerOptimus/SuperAGI#581]
Ability to add custom tools to SuperAGI from a Github repo link. To encourage custom tool building and making the process easy, a how-to doc and a cookie-cutter repo for the custom SuperAGI Tool should be created.

**Comment by neelayan7** [comment]
You can now add your external tools via GUI. Live along with v0.0.7 release. Closing this issue.
