### ISSUE TITLE
Instruction led agent trajectory finetuning

### ISSUE THREAD

**Issue by TransformerOptimus** [TransformerOptimus/SuperAGI#599]
Agent Instructions are a set of directives appended into an agent during its provisioning phase.

Acting as a guidebook for the agent, these instructions help the agent achieve its objective with a higher degree of efficacy, reducing the need for ‘first principles’ thinking for every run and also helping it avoid the dreaded ‘Agent Loops’

**Comment by Troubladore** [comment]
@TransformerOptimus  - are you thinking about something like this?: https://paperswithcode.com/paper/reflexion-an-autonomous-agent-with-dynamic
