### ISSUE TITLE
Agent Performance Monitoring

### ISSUE THREAD

**Issue by Prasaanth-Vallabhan** [TransformerOptimus/SuperAGI#62]
Agent Metrics could be

num of iterations, accuracy of objective achievement, number of times it needed course correction, token usage, errors, loops,

**Comment by Cptsnowcrasher** [comment]
Have been thinking about it. What all metrics would be relevant to track in this

**Comment by neelayan7** [comment]
Duplicate issue: https://github.com/TransformerOptimus/SuperAGI/issues/574 Tracking this here.
