### ISSUE TITLE
Anonymise sensitive data

### ISSUE THREAD

**Issue by digitalgenics** [TransformerOptimus/SuperAGI#657]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

MacOS

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

When adding Access tokens & sensitive data, I see that it does not get filtered. This is a small security issue.
Can you anonymize the data when it is saved and make sure this is stored safely? 

As I can also see that you are deploying the web app, does this information get encrypted when sending/saving it? 

### How to replicate your Issue?

Connecting different services in SuperAGI

### Upload Error Log Content

d

**Comment by neelayan7** [comment]
Thanks for raising this issue!
We encrypt and store OpenAI keys as of now. We recently shifted tool configuration keys to a different table and hence they are not being encrypted and stored. But it's a work in progress. It'll be done soon.

**Comment by JohnHunt999** [comment]
We have the fix ready for this and we are merging it to main in next release. It is already encrypted in the webapp.

**Comment by digitalgenics** [comment]
Great! Always ready to help if needed. Thanks a lot for taking this into account. 
Have a great day
