### ISSUE TITLE
Support for loading different types of document eg. CSV, JSON, SQL etc.

### ISSUE THREAD

**Issue by eqxwow** [TransformerOptimus/SuperAGI#67]
Need to support for loading diff document types CSV, JSON, SQL, etc.

**Comment by erkkimon** [comment]
Came here to add PDF because I think much background information is in that format.

**Comment by georganix** [comment]
And XML format as well as there's plenty of data written available in that format.

**Comment by neelayan7** [comment]
This is now live. Closing this issue.
