### ISSUE TITLE
Main test fail 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#676]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Im getting many error on tests )-

### How to replicate your Issue?

im running the test but many are failing how can i select and copy the test that are failing 

### Upload Error Log Content

docker compose logs

**Comment by neelayan7** [comment]
How are running the tests? Please upload relevant logs

**Comment by neelayan7** [comment]
All the tests are working.

**Comment by DMTarmey** [comment]
IM trying to use test app in vs code, then im trying using cmd pallet im just missing somethink !!
________________________________

**Comment by DMTarmey** [comment]
IM USING PYTEST

**Comment by DMTarmey** [comment]
AND IM CHOOSING TEST DIRECTORY

**Comment by DMTarmey** [comment]
I have finial resolved it after re installing dependencies.
