### ISSUE TITLE
issues with google client id 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#685]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Access blocked: This app’s request is invalid

fit.it.rite@gmail.com
You can’t sign in because this app sent an invalid request. You can try again later or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

### Upload Error Log Content

docker compose logs

**Comment by DMTarmey** [comment]
i think you have fixed the issue

**Comment by neelayan7** [comment]
Yes this has been fixed.
