### ISSUE TITLE
How to set up tool kit 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#689]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

How do i go about setting up the tool kit to add tools from gethub

### Upload Error Log Content

docker compose logs

**Comment by DMTarmey** [comment]
do i need to download pip install superagi-tools

**Comment by neph1** [comment]
This guide:
https://superagi.com/adding-your-own-custom-tool-toolkit-to-superagi/
And look at the existing toolkits in superagi/tools for reference. 
Don't forget to implement BaseToolKit in you _toolkit.py file!

**Comment by DMTarmey** [comment]
were is instruction to work out how to add new tools ? like im building the Pomodforo app you put in example's so i can see how it works, how do i make that file into a template for a tool to add to the tool chest

**Comment by DMTarmey** [comment]
i worked it out
