### ISSUE TITLE
Agent embeddings templates

### ISSUE THREAD

**Issue by eqxwow** [TransformerOptimus/SuperAGI#69]
Need templates for agent embeddings for giving better initial context to the agent. The templates could be created around different goals, constraints, agent types etc.

**Comment by john-vargo** [comment]
Do you have an example of an agent embedding template?  How would these be formed and introduced into the application?

**Comment by JohnHunt999** [comment]
Knowledge embeddings are now live on local and Cloud. Please check it out, it should solve your usecase. Closing this issue
