### ISSUE TITLE
Adding "Knowledge" (memory module) to the SuperAGI

### ISSUE THREAD

**Issue by ResoluteStoic** [TransformerOptimus/SuperAGI#70]
There should be a 'Knowledge' vector database index to add any domain knowledge required by the agents to execute nuanced tasks better. This index can have different metadata tags if there is requirement for splitting the "Knowledge" index.

In summary, the agents should be able to access short term memory & long term memory of tasks/chats in conjugation with optional accessible domain knowledge domain (e.g. experts of the domain, best practices, legal docs) and organisational knowledge to perform the task at hand incrementally better.

**Comment by Cptsnowcrasher** [comment]
Basically you mean list of embeddings for particular domain, which can be plugged to an agent. 

Say all the marketing knwoledge of seo avaiable as embeddings , which can be then used by an agent to achieve his objective

**Comment by Cptsnowcrasher** [comment]
We are planning a marketplace of embeddings to solve this

**Comment by JohnHunt999** [comment]
This feature has been added in v0.0.9. Closing this issue.

**Comment by matari** [comment]
You should be able to add more than one knowledge document to an agent.  for example a langchain doc and openai doc for ai projects.
