### ISSUE TITLE
Issue authorising google calendar 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#700]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Iv tried different way so I'm reaching out Access blocked: This app’s request is invalid

superagi33@gmail.com
You can’t sign in because this app sent an invalid request. You can try again later or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

### Upload Error Log Content

docker compose logs

**Comment by neelayan7** [comment]
Have you followed all steps written in the Readme.md?

**Comment by Tarraann** [comment]
The updated code for the new redirect uri will be merged soon.

**Comment by DMTarmey** [comment]
has this been merged yet ?

**Comment by JohnHunt999** [comment]
This issue occurs when the redirect url is not setup properly while obtaining the keys from google calender. Make sure this is done. We have checked this extensively and google calender seems to work when the setup is done right. If this issue still persists please feel free to ask for assistance on discord. Closing this issue.
