### ISSUE TITLE
Manually change the steps as it say 3 at moment

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#702]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Would be nice to have access to all the data being fed to the software to make tweeks and experiment with, i know agi software had issue with just searching and making long list but not doing anything, but in some ways superAGI is not completing some project, 

### Upload Error Log Content

docker compose logs

**Comment by neelayan7** [comment]
Please consider moving this issue to the Discussion Forum/Discord.
