### ISSUE TITLE
Issue connecting to plugin rabbitmq

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#717]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

u have downloaded this plugin to test the plugin abilities im not sure if it installed correctly, and are theses details the standerd detail for this software https://app.screenclip.com/312g

### Upload Error Log Content

docker compose logs

**Comment by zhound420** [comment]
This is my project under development. A couple of issue to resolve before its functional. I welcome anyone to help with the project.

**Comment by DMTarmey** [comment]
ok how can i help ?

**Comment by neelayan7** [comment]
@luciferlinx101 can you help out?

**Comment by luciferlinx101** [comment]
@zhound420 Hey how can I help you out? I am luciferlinx in discord we can discuss further if needed.
