### ISSUE TITLE
voting on feature request 

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#718]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

would it be possible for you to include upvoting as a way for you to know how many people are interested in a particular report ?

### Upload Error Log Content

docker compose logs

**Comment by neelayan7** [comment]
Please move this issue to a discussion.
