### ISSUE TITLE
no scroll bare when creating new agent !!!!

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#719]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when i start new agend there is no scrol bare and pushing on my middle button dosnt work to creat scroll bar here is image https://app.screenclip.com/2XUG and i have to chamge the size of text so i can see the start button at bottom https://app.screenclip.com/2XUG

### Upload Error Log Content

docker compose logs

**Comment by neph1** [comment]
Yes, very frustrating. I've found that if I click around in the middle area of the page, I can usually use the mouse wheel to scroll.

**Comment by sirajperson** [comment]
I have been using tab and shift+tab to navigate.

**Comment by neelayan7** [comment]
Yeah, we have noticed this. Thanks for raising! We're getting this fixed in the next release!

**Comment by clappo143** [comment]
Zooming out the browser view is another workaround

I used to encounter this issue (though haven't in a week or so)

**Comment by DMTarmey** [comment]
> Yeah, we have noticed this. Thanks for raising! We're getting this fixed in the next release!

great to here well done amazing project

**Comment by JohnHunt999** [comment]
This fix has been done in v0.0.8. Closing this.
