### ISSUE TITLE
Service GUI failed to build

### ISSUE THREAD

**Issue by NadarBharat** [TransformerOptimus/SuperAGI#720]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Step 4/9 : RUN npm ci
 ---> Running in 2170f2dc13ea
node[6]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7a940 node::Abort() [node]
 2: 0xb7a9be  [node]
 3: 0xbe98be  [node]
 4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb395ab node::Start(int, char**) [node]
 7: 0x7ff7f7fc918a  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7ff7f7fc9245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xabbdee _start [node]
Aborted
ERROR: Service 'gui' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 134

### Upload Error Log Content

1

**Comment by neelayan7** [comment]
Is the issue persisting when you re-run?

**Comment by NadarBharat** [comment]
This was due to node version, edited this to node:16, worked but got error service celery failed to build
