### ISSUE TITLE
DockerfileCelery don`t update tools requirements

### ISSUE THREAD

**Issue by myth12315** [TransformerOptimus/SuperAGI#721]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Tools

### Describe your issue.

I installed a plugin but when using the plugin after startup, celery keeps reporting errors not finding the module

requirements.txt
superagi-tools~=1.0.6
mechanize~=0.4.8

### How to replicate your Issue?

 Maybe update the DockerfileCelery add

RUN chmod +x install_tool_dependencies.sh
RUN ./install_tool_dependencies.sh

### Upload Error Log Content

ModuleNotFoundError: No module named 'mechanize‘

**Comment by neelayan7** [comment]
By plugin, do you mean toolkit?
If yes, please send the github repo link as well of the tool.

**Comment by luciferlinx101** [comment]
@myth12315 Hey can you send you tool link we are fixing some bugs and releasing out soon, you should not encounter it again.
