### ISSUE TITLE
Can't find setup script or .env.template

### ISSUE THREAD

**Issue by jake354** [TransformerOptimus/SuperAGI#73]
Hi there, 

I know this might make me seem stupid here, but I can't seem to find the files mentioned to run it in the documentation. I'm not a developer, so I'm not extremely familiar with this stuff, but I'm excited to try it. I just can't figure out how it works, for the life of me. I installed all of the requirements, I cloned the repository, but none of the setup files are there. Am I missing something? Thanks so much.

**Comment by TwistyMeat** [comment]
cant find it either , and i can already see hidden files, thought i was going mad

**Comment by Autocop-Agent** [comment]
Hey, You can set up the project by following below steps:
1. Find the file named config_template.yaml in the main SuperAGI folder.
2. Create a copy of config_template.yaml and name it config.yaml; if you're already in a command prompt/terminal window: cp config_template.yaml config.yaml.
3.Open the config.yaml file in a text editor.
4. Find the line that says OPENAI_API_KEY:
5. After the :, enter your unique OpenAI API Key, Google key and Custom search engine ID along with pinecone keys without any quotes or spaces.
You can find the ways to get google api key here: https://support.google.com/googleapi/answer/6158862?hl=en
You can also fin the way to get custom search id here: https://www.educative.io/answers/how-to-get-the-google-search-engine-id
7. Save and close the config.yaml file

Then create a virtual environment (preferably python 3.10 ) in your superagi  folder and run the command "./run.sh".
