### ISSUE TITLE
Improvement to GUI

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#732]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

IM using my screen length wise to get all the code on the same page and in this configuration the agent and tool kit button are waiting my width of text, can those buttons be moved, also the right box on right can that also have a hide menu option, cheer for you consideration.  

### Upload Error Log Content

docker compose logs

**Comment by neelayan7** [comment]
Please move this issue to Discussions.

**Comment by DMTarmey** [comment]
Ok will do sorry didn’t realise you was using discussion

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DMTarmey** [comment]
moved cheer
