### ISSUE TITLE
Google Search Tool Not working

### ISSUE THREAD

**Issue by sebasvelasquez1** [TransformerOptimus/SuperAGI#738]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Web Version

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

Helo I keep getting this on the online SUperAGI Tool GoogleSearch returned: Error1: [Errno 2] No such file or directory: 'config.yaml', FileNotFoundError, args: {'query': 'most reputable websites on spirituality'}

### How to replicate your Issue?

AGENT NAME: NewsletterSuperAGI

Thoughts: Goal 1 is the first step in the overall process, so it makes sense to start there. By finding reputable websites in this niche, we can gather valuable information for the subsequent goals.
Plan: - Use the GoogleSearch tool to search for reputable websites on spirituality, yoga, meditation, and wellness.
- Extract the websites and their rankings from the search results.
- Evaluate the websites based on their reputation and relevance to the niche.
- Document the findings for future reference.
Criticism: I need to ensure that the search query I use is specific enough to yield relevant results. Additionally, I should consider using multiple search queries to cover a wider range of websites in the niche.
Tool: GoogleSearch
schedule-icon
9 minutes ago
🛠️
Tool GoogleSearch returned: Error1: [Errno 2] No such file or directory: 'config.yaml', FileNotFoundError, args: {'query': 'reputable websites on spirituality, yoga, meditation, and wellness'}
schedule-icon
9 minutes ago
💡
Thoughts: One alternative method is to manually search on Google using a web browser. This will allow me to gather information about the top-ranking websites in the niche.
Plan: - Open a web browser.
- Manually search for reputable websites on spirituality, yoga, meditation, and wellness.
- Take note of the websites and their rankings.
- Evaluate the websites based on their reputation and relevance to the niche.
- Document the findings for future reference.
Criticism: Manually searching on Google may be time-consuming, and there is a possibility of missing out on some relevant websites. It would be helpful to have a tool that can extract the search results automatically.
schedule-icon
9 minutes ago
🛠️
Error2: {'error': "Incomplete tool args: {'thoughts': {'text': 'Since the GoogleSearch tool returned an error, I will need to use an alternative method to search for reputable websites on spirituality, yoga, meditation, and wellness.', 'reasoning': 'One alternative method is to manually search on Google using a web browser. This will allow me to gather information about the top-ranking websites in the niche.', 'plan': '- Open a web browser.\\n- Manually search for reputable websites on spirituality, yoga, meditation, and wellness.\\n- Take note of the websites and their rankings.\\n- Evaluate the websites based on their reputation and relevance to the niche.\\n- Document the findings for future reference.', 'criticism': 'Manually searching on Google may be time-consuming, and there is a possibility of missing out on some relevant websites. It would be helpful to have a tool that can extract the search results automatically.', 'speak': 'Since the GoogleSearch tool encountered an error, I will manually search for reputable websites on spirituality, yoga, meditation, and wellness using a web browser. I will evaluate the websites based on their reputation and relevance to the niche.'}}"}.
schedule-icon
9 minutes ago
💡
Thoughts: Goal 1 requires finding reputable websites in the niche, and a tool that can perform a web search and extract relevant information would be ideal.
Plan: - Use the WebScraperTool to scrape website URLs and extract text content from the search results.
- Specify the search query to target reputable websites on spirituality, yoga, meditation, and wellness.
- Extract the URLs and relevant information from the search results.
- Evaluate the websites based on their reputation and relevance to the niche.
- Document the findings for future reference.
Criticism: I need to ensure that the WebScraperTool is configured correctly to extract the desired information from the search results. Additionally, I should consider using multiple search queries to cover a wider range of websites in the niche.
Tool: WebScraperTool
schedule-icon
9 minutes ago
🛠️
Tool WebScraperTool returned: Filters and Topics Filters and Topics Search Results 45 Best Spiritual Wellness Blogs & Websites 17 Best Spiritual & New Age Blogs [2023 Update] The 10 Best Health and Wellness Websites of 2023 15 Spiritual Blogs, Websites, and Influencers! Best Spirituality Blogs and Websites Top 25+ Spiritual Blogs To Follow Daily In 2022 Spirituality+Health: Home 21 Best Spiritual Blogs of All Times Best Yoga, Meditation, Health & Spirituality Websites & Blogs 58+ Meditation Blogs (Articles for Yoga and Spirituality Seekers) Page Navigation More results Try again Footer Links
schedule-icon
9 minutes ago
💡
Thoughts: Goal 1 involves evaluating the reputation and relevance of the websites found in the search results. To accomplish this, I can use a combination of manual assessment and online tools.
Plan: - Manually visit each website and assess its reputation based on factors like credibility, expertise, and user reviews.
- Use online tools like Alexa Rank, Domain Authority, and Trust Flow to gather additional data on the reputation of the websites.
- Document the findings for each website, including its reputation ranking and relevant metrics.
Criticism: I need to ensure that I have a comprehensive list of reputable websites to evaluate. It's important to consider both well-known websites and lesser-known but highly respected sources in the niche.
Tool: Manual Assessment and Online Tools

### Upload Error Log Content

Tool GoogleSearch returned: Error1: [Errno 2] No such file or directory: 'config.yaml', FileNotFoundError, args: {'query': 'reputable websites on spirituality, yoga, meditation, and wellness'} schedule-icon

**Comment by neelayan7** [comment]
Have you created the config.yaml file? Please read the readme.

**Comment by DMTarmey** [comment]
Take as look at theses videos https://www.youtube.com/results?search_query=install+superagi once your done connect with me on and read this page https://github.com/TransformerOptimus/SuperAGI

**Comment by DMTarmey** [comment]
connect with me on https://discord.com/channels/919289486771380274/919289486771380276 and ill help you if you wish.

**Comment by sebasvelasquez1** [comment]
Wow thank you guys so much !

**Comment by luciferlinx101** [comment]
> Have you created the config.yaml file? Please read the readme.

@sebasvelasquez1 since you are using web version setting up keys in frontend specially for tool being used and open AI key would help you.
