### ISSUE TITLE
uvloop cannot be installed on windows

### ISSUE THREAD

**Issue by cranyy** [TransformerOptimus/SuperAGI#82]
(i am quite new at this so please dont hate too much if there is a simple solution to this)

But everytime I try to run on windows, when it goes through the installation of the reqs, it always dies here:

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\marin\AppData\Local\Temp\pip-install-znu68v0c\uvloop_b16b8985c02e41edaa5ea05f5c3f7949\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

**Comment by nihirag** [comment]
Hey can you comment this [line](https://github.com/TransformerOptimus/SuperAGI/blob/bf4d01e6dd73f556da0c17c974f17c8a8b5aa40d/requirements.txt#LL82C2-L82C15) and try running it again? 

We are working on this. For updates join this [discord channel](https://discord.gg/dXbRe5BHJC)

**Comment by cranyy** [comment]
it does run the test.py but it just uses random prompts, and i cant interract at all, and it doesnt elicit the webpage that is in your screens (unless i am dead wrong about everything again)

**Comment by TransformerOptimus** [comment]
@cranyy Please checkout the branch v0.0.3. It's a dev branch with latest code.
Also note, out GUI is work in progress. So for now, the agent will run only in Terminal. 

Thanks for pointing these items. We will be updating the readme soon.

**Comment by Exarchias** [comment]
Hello everyone, I'm interested in this issue and would like to work on solving it. I need to familiarize myself with the project anyway, so it seems like a good starting point. Please bear in mind that this might be a dead-end, but if there's a solution out there, I'm determined to find it. I'll post my notes here for transparency. Please note that this is my first legit open source participation, but I'm not new to issues and PRs.

**Comment by neelayan7** [comment]
We have removed uvloop dependency from requirements.txt. So closing this issue.

**Comment by Exarchias** [comment]
Awesome! Thank you for the headsup.
