### ISSUE TITLE
twitter tool not working on https

### ISSUE THREAD

**Issue by AndrukhivAndriy** [TransformerOptimus/SuperAGI#845]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Linux

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Tools

### Describe your issue.

Hi. I deploy SuperAGI on https webhost(Ubuntu 22) by modifying /nginx/default.conf and docker-compose.yml . I changed everywhere in code "https://localhost:3000/..." to "https://MYHOSTNAME/". SuperAGI works fine, but Twitter tool can not auth on Twitter (when I press the button "Authenticate Tool") and I got the error from Twitter: "Whoa there! The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake." URI: "https://api.twitter.com/oauth/authenticate?oauth_token=undefined" I changed API, API KEY - no changes, another account - no changes. How to solve it? I need SuperAGI+TwitterTool post results on Twitter. Thanks.  
![Screenshot_1](https://github.com/TransformerOptimus/SuperAGI/assets/79985930/a238ed4f-e042-4285-84d4-cd26200f4ed8)

### How to replicate your Issue?

Goal: Write a nice text about Google and post it on Twitter
LLM: gpt-3.5, gpt4

### Upload Error Log Content

This error appears on web interface: Tool Send Tweets Tool returned: Validation Error in args: 2 validation errors for SendTweetsInput is_media   field required (type=value_error.missing) media_files   field required (type=value_error.missing), args: {'tweet_text': 'Google is a remarkable company that has revolutionized the way we search for information, collaborate on documents, and navigate the world. #Google #Technology'} . After that - Thinking....

**Comment by SufferingBug** [comment]
I Noticed that there was no where to put The api Keys for Twitter under the config.yamil

**Comment by yaronelh** [comment]
Trying to use the tool on the cloud produces the same error

**Comment by Tarraann** [comment]
> I Noticed that there was no where to put The api Keys for Twitter under the config.yamil

You would have an option for toolkits at the sidebar, Select Twitter over there, update your api keys and authenticate it. config.yaml would only update but not follow the oauth flow.

**Comment by AndrukhivAndriy** [comment]
Of course, i did it. updated api key for a few times. When I try to authenticate it - got an error

**Comment by Tarraann** [comment]
You have written uri as https://localhost:3000 if I am not wrong use it as http://localhost:3000. And you do not need to make any change in code. In your Twitter developer account add two redirect uri one for local and another for cloud. The uri's are http://localhost:3000/api/twitter/oauth-tokens
https://app.superagi.com/api/twitter/oauth-tokens

**Comment by Tarraann** [comment]
If it still shows the error can you share the settings for your Twitter developer account

**Comment by Tarraann** [comment]
For localhost make sure to keep it http and not https

**Comment by JohnHunt999** [comment]
Please make sure that twitter tool has been setup properly. We have checked this from our end and if the setup is done properly, twitter tool works. You can ping us on discord if you require any assistance. Closing this issue.
