### ISSUE TITLE
Unable to run superagi with gpt-3.5

### ISSUE THREAD

**Issue by mayuroks** [TransformerOptimus/SuperAGI#89]
I tried running superagi with gpt-3.5 it gives an error. With gpt-4 it's working fine. Please look into this.

**Comment by SalemHella** [comment]
hi I am looking to contribute can I have this issue

**Comment by Cptsnowcrasher** [comment]
I think this issue has already been picked by @COLONAYUSH

**Comment by Cptsnowcrasher** [comment]
@SalemHella do you want to pick this feature  https://github.com/TransformerOptimus/SuperAGI/issues/114  ? or you can go though issues list

**Comment by SalemHella** [comment]
@Cptsnowcrasher I don't mind looking for another one if this one is taking
