### ISSUE TITLE
Integrate with Weaviate db

### ISSUE THREAD

**Issue by Cptsnowcrasher** [TransformerOptimus/SuperAGI#93]

**Comment by hsm207** [comment]
I would like to implement this integration.

**Comment by eqxwow** [comment]
@hsm207 Thanks for showing interest. I have assigned this issue to you.

We have Pinecone integration in place. We need a similar implementation for Weaviate. 

Join our Discord community https://discord.gg/Ur49PSWA 
I will guide you with the code implementation and then you can implement the rest.

**Comment by hsm207** [comment]
@eqxwow what's your handle on Discord?

**Comment by neelayan7** [comment]
Closing this as this is done.
